### ISSUE TITLE
作者，你好，可以支持sqlite3作为数据库吗？

### ISSUE THREAD

**Issue by dianso** [Jinnrry/PMail#1]
作者，你好，可以支持sqlite3作为数据库吗？

我的内存小，不想安装mysql了

**Comment by Jinnrry** [comment]
不至于吧？我512M的服务器装MySQL都没啥压力。MySQL也就占十多兆的内存而已。

**Comment by ajsdhfb** [comment]
+10086，mysql 太重了

**Comment by Jinnrry** [comment]
那我这周加个数据库驱动吧，应该就几行代码改动

**Comment by Jinnrry** [comment]
#3 已经支持了
