### ISSUE TITLE
数据库支持可以增加postgres吗

### ISSUE THREAD

**Issue by vvxu** [Jinnrry/PMail#101]
rt数据库支持可以增加postgres吗

**Comment by Jinnrry** [comment]
增加pg的主要优势是啥？因为目前支持了sqlite，为了兼容，也不可能使用pg的高级特性，反而增加维护难度

**Comment by Jinnrry** [comment]
之前为了追求项目的轻量，数据库操作选用了sqlx，所有sql都是直接手写的，导致多数据库维护费劲。刚刚review了一下，要增加pg支持的话就得考虑改成gorm或者xorm框架了

**Comment by muyiacc** [comment]
其实pg还是很轻量的，MySQL内存占用很高（默认安装的MySQL不做限制，光服务300M左右内存就没有了），但是从普适性来说MySQL还是强，用sqlite感觉每次读取没那么快吧，我有个博客，也是用的sqlite，每次打开后台编辑新文章加载就很慢。说回pmail，对于个人使用来说，这个邮箱我只是用来接受一些不太重要的邮件，使用频率不太高，所以打开速度不是太大问题

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/PMail/blob/master/server/db/init.go#L21

其实这里改一下，加个pg类型就行了。但是后续开发测试成本太高了，现在mysql、sqlite两个我每次改完代码测一遍都很费劲了。

**Comment by 456vv** [comment]
个人看法：语法不兼容，mail这类系统用sqlite就足够了。

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/PMail/releases/tag/v2.6.0

这个版本支持了
