### ISSUE TITLE
镜像拉取失败，启动文件失败

### ISSUE THREAD

**Issue by Leo4ML** [Jinnrry/PMail#102]
服务器是华为云，系统是CentOS7
【问题一：镜像拉取失败】
不论是
docker pull ghcr.io/jinnrry/pmail:v2.4.2@sha256:14574477276e84a4df7c36afd48187045b7d86080b187666d199a4296ad6ea0b
还是执行
docker pull ghcr.io/jinnrry/pmail:v2.4.2
结果都是Error response from daemon: manifest unknown
【问题二：启动文件失败】
放弃docker方式，从release中下载amd64的文件至华为云服务器中执行pmail文件
![image](https://github.com/Jinnrry/PMail/assets/32268546/0a4ea6fb-b78f-49e1-a2cd-94cbaacd99df)
从打印的日志看，似乎是在80端口启动了，查看端口占用：
![image](https://github.com/Jinnrry/PMail/assets/32268546/e0c36f5b-f4bf-4e00-a169-93b6f1294991)
也显示80端口被使用，但是在浏览器中输入华为云服务器公网ip打开pmail，chrome显示无法访问此网页。
请问我该怎么解决这些问题呢，如果还需要其他更多信息，请告知，如能解决问题，非常感谢！

**Comment by Jinnrry** [comment]
在你机器上直接执行`curl 127.0.0.1` 是什么结果呢

**Comment by Leo4ML** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by Jinnrry** [comment]
或者用`pmail -p 8888` 这样可以换端口启动

**Comment by Leo4ML** [comment]
> 在你机器上直接执行`curl 127.0.0.1` 是什么结果呢

今天新启动pmail，试了下，有对应的html结果，遂浏览器打开，可以正常看到pmail的前端页面了！

**Comment by Jinnrry** [comment]
你用`docker pull ghcr.io/jinnrry/pmail:latest` 拉取试试呢，我用美东和香港的机器测试都是能正常拉下来的。

**Comment by Leo4ML** [comment]
> docker pull ghcr.io/jinnrry/pmail:latest

这个命令可以，感谢！

**Comment by Leo4ML** [comment]
镜像拉取问题已解决，启动文件后无法打开网页该问题无法复现，目前我的服务器未做任何修改的情况又可以通过ip打开pmail页面。
