### ISSUE TITLE
WEB初始化第六步SSL设置失败

### ISSUE THREAD

**Issue by Leo4ML** [Jinnrry/PMail#104]
按照页面提示在第六步一直报错，报错内容如下
![image](https://github.com/Jinnrry/PMail/assets/32268546/d8a4246a-c294-4c08-9df5-ba4a0fc1829f)
看报错说是我的dns设置不对，但是已经按照setup的提示添加了dns记录，目前我的dns记录如下
![image](https://github.com/Jinnrry/PMail/assets/32268546/b6ad32cc-c9ae-4060-87aa-d359924bf1f4)
![image](https://github.com/Jinnrry/PMail/assets/32268546/f055f86b-64f7-423c-9c6b-d87ba6e78452)
我的端口开放规则如下
![image](https://github.com/Jinnrry/PMail/assets/32268546/d3ec31e3-b1f2-43b5-98e6-e66937c7dda8)
我的pmail目前config内容如下
![image](https://github.com/Jinnrry/PMail/assets/32268546/9243cf8a-29f8-425f-9ea7-eb1e20f2b76a)
打码的皆是域名和ip，请问是我哪里配置错了吗

**Comment by Jinnrry** [comment]
DNS的ip是127开头的?

**Comment by Leo4ML** [comment]
> DNS的ip是127开头的?

woc！ 自己检查永远检查不出自己的问题，我的ip是121开头，这半个月以来我写的一直是127，期间试过mailserver，postfix，全都不行，麻了！感谢大佬，我重新试一下。

**Comment by Leo4ML** [comment]
> DNS的ip是127开头的?

更正完IP后，可以解析对应的dns记录。但出现了新的报错，如下图
![image](https://github.com/Jinnrry/PMail/assets/32268546/2deccef8-4a0a-4c78-ab3c-64af96c09c6f)

**Comment by Jinnrry** [comment]
你把程序关了重启一下呢，看起来像是你上一次的挑战记录还在，又新建了挑战，两次秘钥对不上导致的

**Comment by Leo4ML** [comment]
> 你把程序关了重启一下呢，看起来像是你上一次的挑战记录还在，又新建了挑战，两次秘钥对不上导致的

有试过重启。我需要把config目录删掉吗?

**Comment by Jinnrry** [comment]
config也删了吧，重试一下

**Comment by Leo4ML** [comment]
> config也删了吧，重试一下

关闭程序--删除config目录--drop pmail数据库--新建pmail数据库--启动pmail--按web提示配置--更新dns内容，依然报错ssl相关问题
![image](https://github.com/Jinnrry/PMail/assets/32268546/18e1166c-70dd-486b-981e-c4db9b98af94)

**Comment by Jinnrry** [comment]
`curl -i http://smtp.xxxxxxxx.cn/.well-known/acme-challenge/5c-U................CeuDY` 看看输出啥呢

**Comment by Jinnrry** [comment]
日志中有`AcmeChallenge` 相关的吗

**Comment by Leo4ML** [comment]
> 日志中有`AcmeChallenge` 相关的吗

pmail的日志文件在哪里，pamil目录下没找到

**Comment by Jinnrry** [comment]
你是直接运行程序的还是docker运行的？直接运行的话控制台就会输出日志，Docker运行的话执行docker logs -f xxxx

**Comment by Jinnrry** [comment]
我看了下代码，ACM记录不匹配返回的http code是404，403状态码应该不是PMail程序返回的。你这个ip上还有nginx之类的网关吗

**Comment by Jinnrry** [comment]
你执行`curl -i http://smtp.xxxxxxxx.cn/.well-known/acme-challenge/5c-U................CeuDY` 然后看你日志中有没有输出`AcmeChallenge` 日志，如果没有日志的话说明你中间网关有问题，请求没有到PMail程序

**Comment by Jinnrry** [comment]
结合你 #102 这个ISSUE说的，PMail程序启动了，但是Chrome没法访问，我感觉大概率是你服务器还有其他网关，请求走到其他地方去了，没到PMail程序

**Comment by Leo4ML** [comment]
> 结合你 #102 这个ISSUE说的，PMail程序启动了，但是Chrome没法访问，我感觉大概率是你服务器还有其他网关，请求走到其他地方去了，没到PMail程序
我curl了一下，结果如下图
![image](https://github.com/Jinnrry/PMail/assets/32268546/436f3838-85c6-452c-a2aa-0f6e7cf96284)
我这个服务器是新申请的，没有启动其他内容。前面用docker启动过mailserver和postfix，但是现在都关掉了。我也没配置nginx相关。
#102 这个ISSUE里提到的，无法正常打开，我也有点奇怪。如果还有其他网关的话，我先排查下。

**Comment by Jinnrry** [comment]
这个404应该是到了PMail程序了，ACME挑战结束后就会清除Token，所以就404了。但是你报错那个，我总感觉是流量没请求到程序。 我没用过华为云的服务器，但是腾讯、阿里之类的，如果你域名没备案、服务器没实名，会给你拦截，然后跳到备案地址去。会不会是你的域名、IP被华为云拦截了？

**Comment by Jinnrry** [comment]
你在本机请求能够请求通，一切都正常。但是外网访问的时候就拦截了。这样刚好吻合你的403状态码

**Comment by Leo4ML** [comment]
> 这个404应该是到了PMail程序了，ACME挑战结束后就会清除Token，所以就404了。但是你报错那个，我总感觉是流量没请求到程序。 我没用过华为云的服务器，但是腾讯、阿里之类的，如果你域名没备案、服务器没实名，会给你拦截，然后跳到备案地址去。会不会是你的域名、IP被华为云拦截了？
我按照你的提示，做了检查。
服务器实名了
![image](https://github.com/Jinnrry/PMail/assets/32268546/043147c1-947a-45ae-b106-00c9dcb8e29b)
域名没有备案，这里我是对pmail.xxxx.cn做备案还是www.leodaren.cn呢？（如果域名备案才能正常使用，岂不是我每开一个三级域名 A.xxxx.cn，都要为这个三级域名A做一次备案了？）
目前dns的所有记录，都可以解析到。如下图
![image](https://github.com/Jinnrry/PMail/assets/32268546/544b0c07-1736-4351-9cc0-85ff94382feb)
![image](https://github.com/Jinnrry/PMail/assets/32268546/a685044a-764e-4000-b61b-270c68a09896)
如果还需要其他信息还请大佬告知

**Comment by Jinnrry** [comment]
我差不多10年没自己提交过备案信息了，我也不知道现在备案是啥样的，我感觉应该是提交主域名上去就行吧。

https://github.com/Jinnrry/PMail/commit/ce393211cfef796718235b80ad005e4e89ca11b5

我加了一个ACME失败日志，你先用这个版本测试一下呢。把以前的config和其他文件全删了，用这个版本重新试一下，然后把日志全部贴上来我确认下是不是流量被拦截了

https://github.com/Jinnrry/PMail/releases/tag/v2.4.5pre

**Comment by Leo4ML** [comment]
> 我差不多10年没自己提交过备案信息了，我也不知道现在备案是啥样的，我感觉应该是提交主域名上去就行吧。
> 
> [ce39321](https://github.com/Jinnrry/PMail/commit/ce393211cfef796718235b80ad005e4e89ca11b5)
> 
> 我加了一个ACME失败日志，你先用这个版本测试一下呢。把以前的config和其他文件全删了，用这个版本重新试一下，然后把日志全部贴上来我确认下是不是流量被拦截了
> 
> https://github.com/Jinnrry/PMail/releases/tag/v2.4.5pre

用了新的执行文件后，前端页面报错如下
![image](https://github.com/Jinnrry/PMail/assets/32268546/0de00d32-9efb-463a-a73b-67f97c54825e)

**Comment by Jinnrry** [comment]
弹这个那应该就是你请求被拦截了，ACME服务器连不到你服务器导致403了。我刚刚又测试你一遍证书获取，没拦截的情况下，自动获取证书是没有任何问题的。你解决这个拦截应该就可以了

**Comment by Leo4ML** [comment]
> 弹这个那应该就是你请求被拦截了，ACME服务器连不到你服务器导致403了。我刚刚又测试一遍证书获取，没拦截的情况下，自动获取证书是没有任何问题的。你解决这个拦截应该就可以了

被ssl证书问题困扰很久了，已经提交备案审核了，非常感谢一直指导解答！

**Comment by Leo4ML** [comment]
历时9天，备案完毕。完成了搭建，可以给我的qq邮箱发邮件，收到来自我的qq邮箱邮件。但是，当我尝试用pmail注册如支付宝账户时，会失败，如下图：
![image](https://github.com/Jinnrry/PMail/assets/32268546/0d149af4-ba49-40ef-b8e0-b87970d584c7)

**Comment by Jinnrry** [comment]
这个和PMail程序没有任何关系了，阿里写死了邮箱白名单。或者是风控策略拦截了

**Comment by Leo4ML** [comment]
感谢。pmail目前已通过qq邮件收发测试。
