### ISSUE TITLE
smtp  一下子发超过3个人 docker就知道关闭了 

### ISSUE THREAD

**Issue by cht870422** [Jinnrry/PMail#105]
**请说明问题 / Describe the bug**
smtp  连续3次 docker就知道关闭了 
**如何复现 / To Reproduce**
# mail_sender.py
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.header import Header

# 设置SMTP服务器地址和端口
smtp_server = 'smtp.域名'
smtp_port = 465  # 对于SSL加密，通常使用465端口

# 设置发件人和收件人邮箱地址
from_addr = 'xiaocao@自己得域名'
to_addr = '收件人@域名'

# 设置邮箱登录凭据
username = 'admin'
password = 'admin'

# 创建MIME邮件对象
msg = MIMEMultipart()
msg['From'] = Header(from_addr)
msg['To'] = Header(to_addr)
msg['Subject'] = Header('邮件主题')

# 邮件正文
body = '这是一封测试邮件。'
msg.attach(MIMEText(body, 'plain', 'utf-8'))

# 连接到SMTP服务器
server = smtplib.SMTP_SSL(smtp_server, smtp_port)
server.set_debuglevel(1)  # 开启调试模式

# 登录SMTP服务器
server.login(username, password)

# 发送邮件
server.sendmail(from_addr, to_addr, msg.as_string())

# 断开与SMTP服务器的连接
server.quit()

**你预期的行为 / Expected behavior**

**贴上你的配置文件 / Program configuration file contents**
<details>
  <summary>config.json</summary>

```
这里贴上你的配置文件内容。
Copy the contents of your configuration file here.
```

</details>

**日志信息 / Log**
<details>
  <summary>log</summary>

```
这里贴上问题相关日志
Copy the contents of your log here.

```

</details>

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/PMail/releases/tag/v2.4.6

这个版本中应该修复了

**Comment by cht870422** [comment]
还是不可以  最新版 --===============3262169505879224294==--

smtp/server 2024/04/20 11:02:51 panic serving 49.79.79.98:35706: interface conversion: interface is nil, not error
goroutine 565 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/emersion/go-smtp.(*Conn).handle.func1()
        /go/pkg/mod/github.com/emersion/go-smtp@v0.21.0/conn.go:98 +0x9a
panic({0xaf1560?, 0xc000484ba0?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
pmail/utils/send.Send.func2({0xac9ee0?, 0xc0001738f0?}, {0x0?, 0x0?})
        /work/utils/send/send.go:191 +0x112
sync.(*Map).Range(0xc000490f40?, 0xc00032ba50)
        /usr/local/go/src/sync/map.go:477 +0x1f8
pmail/utils/send.Send(0xc00027aaa0, 0xc0004b2120)
        /work/utils/send/send.go:190 +0x927
pmail/smtp_server.(*Session).Data(0xc00027aaf0, {0xe2f860, 0xc000490900})
        /work/smtp_server/read_content.go:86 +0xb90
github.com/emersion/go-smtp.(*Conn).handleData(0xc000194630, {0x0?, 0x0?})
        /go/pkg/mod/github.com/emersion/go-smtp@v0.21.0/conn.go:933 +0x191
github.com/emersion/go-smtp.(*Conn).handle(0xc000194630, {0xc000012f88?, 0x138ea60?}, {0x0, 0x0})
        /go/pkg/mod/github.com/emersion/go-smtp@v0.21.0/conn.go:139 +0x14d
github.com/emersion/go-smtp.(*Server).handleConn(0xc0003bc0f0, 0xc000194630)
        /go/pkg/mod/github.com/emersion/go-smtp@v0.21.0/server.go:167 +0x2c5
github.com/emersion/go-smtp.(*Server).Serve.func1()
        /go/pkg/mod/github.com/emersion/go-smtp@v0.21.0/server.go:123 +0xcd
created by github.com/emersion/go-smtp.(*Server).Serve in goroutine 35
        /go/pkg/mod/github.com/emersion/go-smtp@v0.21.0/server.go:120 +0x216

**Comment by Jinnrry** [comment]
你是用上面这个python程序发信的吗？连续执行3次？我始终复现不出来这个问题

**Comment by cht870422** [comment]
我就是用上面脚本发的，现在不是崩溃了。现在是他内部内存还出现错误。，你可以看一下docker logs

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/PMail/releases/tag/v2.4.6

这个版本试下呢

**Comment by cht870422** [comment]
> [https://github.com/Jinnrrry/PMail/releases/tag/v2.4.6](https://github.com/Jinnrry/PMail/releases/tag/v2.4.6)
> 
> 这个版本试下呢

OK，一会再测试一下，因为我记得我昨天你给我回复了过后，我docker 镜像删除了，重新拉取了1次，今天一会我编译打包了一次，看一下，你也可以看一下你ok 邮箱，我们沟通

**Comment by Jinnrry** [comment]
有啥问题就这里沟通吧
