### ISSUE TITLE
我系统增加一个多域名

### ISSUE THREAD

**Issue by cht870422** [Jinnrry/PMail#107]
你这个太好了, 还是比较轻量,我是想作为公司邮箱    以为增加多域名 跟 DMARC

**Comment by Jinnrry** [comment]
目前可以多域名收信，但是发信只能用配置文件中的域名

**Comment by cht870422** [comment]
希望可以增加    可以作为创业小公司邮箱发送验证码

**Comment by Jinnrry** [comment]
发验证码为啥需要多域名？单域名的话现在就可以

https://github.com/Jinnrry/PMail/wiki/%E5%90%8E%E7%AB%AF%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3#6-emailsend

**Comment by cht870422** [comment]
因为 25端口 阿里云  腾讯云都封了  现在其他没有封  减少成本啊  因为公司是3个产品 3个域名 所以没有办法

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/PMail/releases/tag/v2.6.0

这个版本支持了
