### ISSUE TITLE
电信公网无法使用自动获取SSL(无80 443)

### ISSUE THREAD

**Issue by dnslin** [Jinnrry/PMail#108]
**请说明问题 / Describe the bug**
web site的证书是有的，需要配置的是stmp 还是 pop的ssl证书 还是说需要泛解析的证书 

家宽可以正常使用 除开 80 443 以外的所有端口

**Comment by Jinnrry** [comment]
自动获取证书必须要80端口。自己配置的话证书需要匹配
pop.domain
smtp.domain
domain
这3个地址

**Comment by dnslin** [comment]
我通过acme dns 申请了 这三个域名的泛证书 
![image](https://github.com/Jinnrry/PMail/assets/49158572/bd5c8998-c0e5-444c-b6d4-276969f02a40)
但是 访问 我的非标端口 会跳转到 80 或者 443

**Comment by Jinnrry** [comment]
配置文件 `httpsEnabled `改成2
