### ISSUE TITLE
docker版本有详细点的配置吗

### ISSUE THREAD

**Issue by gzldc** [Jinnrry/PMail#11]
如题

**Comment by gzldc** [comment]
docker部署的步骤

**Comment by gzldc** [comment]
docker部署 db选择mysql报错：
at /work/services/setup/db.go:82 at /work/db/init.go:29 default addr for network '.' unknown

**Comment by gzldc** [comment]
选择自动ssl 报错如下：
at /work/services/setup/ssl/ssl.go:124 error: one or more domains had a problem: [mail.daoyanku.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for mail.daoyanku.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for mail.daoyanku.com - check that a DNS record exists for this domain [smtp.daoyanku.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 120.79.35.41: Invalid response from http://smtp.daoyanku.com/.well-known/acme-challenge/rWpt4ln5ZtVuMA-m1WtQwEiumlHytKel7Qiroi0cxf4: 404

**Comment by Jinnrry** [comment]
80、443、25这三个端口需要和本机端口映射，你这个要么是dns配置不对，要么是端口没映射吧

**Comment by Jinnrry** [comment]
docker run -p 25:25 -p 80:80 -p 443:443 -p 465:465 -v $(pwd)/config:/work/config ghcr.io/jinnrry/pmail:latest
