### ISSUE TITLE
删除邮件报错

### ISSUE THREAD

**Issue by onlymyplay** [Jinnrry/PMail#110]
**请说明问题 / Describe the bug**
删除邮件时报错
at /home/runner/work/PMail/PMail/server/services/del_email/del_email.go:18 ID param []int{10} is not supported
![image](https://github.com/Jinnrry/PMail/assets/60839498/d3b65b06-a0ec-4857-9a09-4bc394486eb2)

**如何复现 / To Reproduce**
1. 下载v2.4.6正常运行
2. 勾选邮件后选择删除，确认后报错
3. 
![image](https://github.com/Jinnrry/PMail/assets/60839498/721b26f0-0072-45cf-a754-9f801200c8d7)

**你预期的行为 / Expected behavior**
正常删除
**贴上你的配置文件 / Program configuration file contents**
<details>
  <summary>config.json</summary>

```
这里贴上你的配置文件内容。
Copy the contents of your configuration file here.
{"logLevel":"","domain":"example.cn","domains":null,"webDomain":"pmail.example.cn","dkimPrivateKeyPath":"config/dkim/dkim.priv","sslType":"1","SSLPrivateKeyPath":"config/ssl/private.key","SSLPublicKeyPath":"config/ssl/public.crt","dbDSN":"./config/pmail.db","dbType":"sqlite","httpsEnabled":2,"spamFilterLevel":0,"httpPort":8080,"httpsPort":8081,"weChatPushAppId":"","weChatPushSecret":"","weChatPushTemplateId":"","weChatPushUserId":"","tgBotToken":"","tgChatId":"","isInit":true,"webPushUrl":"","webPushToken":""}
```

</details>

**日志信息 / Log**
<details>
  <summary>log</summary>

```
这里贴上问题相关日志
Copy the contents of your log here.
没看到由这个错误产生的日志
```

</details>

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/PMail/releases/tag/v2.4.7

这个版本修复了

**Comment by onlymyplay** [comment]
> https://github.com/Jinnrry/PMail/releases/tag/v2.4.7
> 
> 这个版本修复了

不能从数据库删除吗？删除到垃圾箱之后就删除不了了

**Comment by Jinnrry** [comment]
目前是只做了软删除，没有考虑彻底删除

**Comment by Jinnrry** [comment]
这个issues先关了，需要彻底删除的话可以再开feature issues讨论
