### ISSUE TITLE
Invalid default value for 'id'

### ISSUE THREAD

**Issue by huozhifeng1** [Jinnrry/PMail#114]
您好， 我是下载的是2.4.6.1安装的   （https://github.com/Jinnrry/PMail/releases/download/v2.4.6.1/linux_amd64.zip）
启动后，通过web进行访问，选择mysql数据库存储的时候，后端提示“Invalid default value for 'id'” ， 请问如果解决。 

![5](https://github.com/Jinnrry/PMail/assets/162943262/b42a3cf1-6db1-4a58-8834-cb621d9fff69)

![报错1](https://github.com/Jinnrry/PMail/assets/162943262/b86011d9-08ab-4457-bd21-2a166d8f9b5f)

**Comment by Jinnrry** [comment]
你看一眼mysql里面email表id字段是不是没加自增？

**Comment by huozhifeng1** [comment]
加了的，而且我看这个表是自动生成的。 
![7](https://github.com/Jinnrry/PMail/assets/162943262/9b3c79d4-c27a-4b5e-8b65-d48a279ab97b)

**Comment by huozhifeng1** [comment]
> 你猛一看mysql里面email表id字段是不是没加自增？
数据库表是自动生成的， 这个是字段截图 您辛苦看下
![7](https://github.com/Jinnrry/PMail/assets/162943262/5645dbac-3c38-4bea-ab0b-6f527939a7e6)

**Comment by Jinnrry** [comment]
我复现出来了，数据库兼容问题。等候我重新发个版本

**Comment by huozhifeng1** [comment]
好的 麻烦了

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/PMail/releases/tag/v2.4.7

这个版本修复了
