### ISSUE TITLE
有人给QQ邮箱发送成功过吗

### ISSUE THREAD

**Issue by Mcdull0921** [Jinnrry/PMail#120]
如果服务器之间只能用25端口通信，那么现在到底什么样的服务器能和腾讯25端口正常通信，用这个软件能给qq邮箱发一封邮件，并能在qq邮箱的收件箱看到这封邮件吗？有人成功过吗？

参考：[issues8](https://github.com/Jinnrry/PMail/issues/8)

**Comment by Jinnrry** [comment]
我个人，搬瓦工美东，搬瓦工香港两台机器测试，PMail 收发QQ邮箱均正常

**Comment by Mcdull0921** [comment]
> 我个人，搬瓦工美东，搬瓦工香港两台机器测试，PMail 收发QQ邮箱均正常

需要找提供商提申请吗，还是直接就能支持？

**Comment by Jinnrry** [comment]
直接就能用，搬瓦工不限任何端口
