### ISSUE TITLE
关于80443被占用，选择使用caddy反向代理管理页面的想法

### ISSUE THREAD

**Issue by haotian2004** [Jinnrry/PMail#129]
caddy是能自动申请证书的，管理页面我想改成用caddy反向代理

**Comment by Jinnrry** [comment]
配置文件里面把`httpsEnabled`设置为2，`httpPort`改成任一端口，然后用caddy反代就行了

**Comment by chaohua27** [comment]
既然是用的ACME协议，希望能把acme的那些证书生成模式都继承过来，比如DNS API模式，这样可以满足任何场景需求。https://github.com/acmesh-official/acme.sh/wiki/How-to-issue-a-cert

**Comment by Jinnrry** [comment]
> 既然是用的ACME协议，希望能把acme的那些证书生成模式都继承过来，比如DNS API模式，这样可以满足任何场景需求。https://github.com/acmesh-official/acme.sh/wiki/How-to-issue-a-cert

DNS API涉及到域名服务商的api，个人精力有限，没时间去适配每个域名服务商的api，同时，个人金钱有限，我也没法在每个供应商那里都买个域名做测试。

**Comment by chaohua27** [comment]
> > 既然是用的ACME协议，希望能把acme的那些证书生成模式都继承过来，比如DNS API模式，这样可以满足任何场景需求。https://github.com/acmesh-official/acme.sh/wiki/How-to-issue-a-cert
> 
> DNS API涉及到域名服务商的api，个人精力有限，没时间去适配每个域名服务商的api，同时，个人金钱有限，我也没法在每个供应商那里都买个域名做测试。

是否能直接做个接口调用acme？如果不方便内置acme，可以考虑让用户自己装，pmail负责调用。原来的模式也保留。

**Comment by Jinnrry** [comment]
> > > 既然是用的ACME协议，希望能把acme的那些证书生成模式都继承过来，比如DNS API模式，这样可以满足任何场景需求。https://github.com/acmesh-official/acme.sh/wiki/How-to-issue-a-cert
> > 
> > 
> > DNS API涉及到域名服务商的api，个人精力有限，没时间去适配每个域名服务商的api，同时，个人金钱有限，我也没法在每个供应商那里都买个域名做测试。
> 
> 是否能直接做个接口调用acme？如果不方便内置acme，可以考虑让用户自己装，pmail负责调用。原来的模式也保留。

什么叫做个接口调用acme？现在就是调用acme接口的，只是没有实现DNS方式验证而已。你现在也可以自己管理证书啊，没有强制要求程序申请证书

**Comment by haotian2004** [comment]
> 建议和alist那种，可以自己开启https指定证书位置开启https，强制80 443占用这个确实有点不太好

就是指的是把后台默认端口改到非80 443
使用一个特定的端口，自动证书没什么必要，毕竟服务器跑的业务多的话不好办这个，得配合反代，比如使用了WordPress搭建博客，我使用smtp服务的情况下就会使用反向代理代理一下管理地址，而且caddy会自动申请证书，完全不用一位一个证书的事情发愁

**Comment by haotian2004** [comment]
> > 建议和alist那种，可以自己开启https指定证书位置开启https，强制80 443占用这个确实有点不太好
> 
> 就是指的是把后台默认端口改到非80 443
> 使用一个特定的端口，自动证书没什么必要，毕竟服务器跑的业务多的话不好办这个，得配合反代，比如使用了WordPress搭建博客，我使用smtp服务的情况下就会使用反向代理代理一下管理地址，而且caddy会自动申请证书，完全不用因为一个证书的事情发愁的/笑哭

顺便提一嘴，配置文件貌似是没有格式化，排版错误，改配置文件不太方便，建议多完善完善功能（比如说多域名的实现）及后台的GUI

**Comment by Jinnrry** [comment]
> caddy反代场景下正确的证书配置应该是什么样的？ caddy会申请web的证书，那么smtp这些服务的证书pmail还会自动申请吗？这种情况下是不是只能dns-01方式？

是，如果使用http的方式验证，pmail和caddy只有一个能占用80端口，另外一个就只能使用dns的方式验证
