### ISSUE TITLE
是不是可以不用 25直接使用 465

### ISSUE THREAD

**Issue by T-bagwell** [Jinnrry/PMail#130]
## 请完整读完[README](https://github.com/Jinnrry/PMail/blob/master/README_CN.md)再提问! / Before asking questions, please read the [README](https://github.com/Jinnrry/PMail/blob/master/README.md) !

我看历史 issue 说是必须用 25，我看还有回复说支持了 465 了，想问一下，还是不能直接用 465 吗？

**Comment by Jinnrry** [comment]
现目前，互联网上所有的电子邮件，均使用SMTP协议进行传输，SMTP协议和HTTP协议一样，在设计之初并没有考虑到安全性，都是明文传输。后来为了传输安全，在SMTP协议的基础上引入了TLS加密。TLS加密有2种方案：
1、SMTP over TLS，也就是SMTPS协议，类似HTTPS，从握手阶段就进行TLS相关加密
2、SMTP + STARTTLS， 握手阶段+HELLO阶段使用明文传输，准备交换信件内容的时候发送STARTLS命令，后续传输使用TLS加密

这两种方案是目前邮件传输过程中保证安全的唯二方案。而其中SMTP over TLS方案使用的端口一般是465，而SMTP+STARTLS使用端口是25

回到能不能只用465的问题，这里得分2种情况来说。

1、用户使用的邮箱客户端（比如MAC OS的“邮件”、Windos的“电子邮件”、已及其他邮箱APP应用），这些客户端程序基本上都是适配了上述两种传输方式的，而且端口都是可以自定义的，也就是说随便服务端是什么端口，是25还是465还是123还是125，根本没影响，爱是多少是多少

2、邮箱服务器和服务器之间的通信（比如PMail服务器和Gmail服务器、GMail和OutLook服务器）。服务端之间的通信，截止目前（2024年），我测试过的主流邮箱服务端，90%都是仅支持SMTP+STARTLS加密方式的。甚至部分服务端（比如搜狐 https://github.com/Jinnrry/PMail/issues/72 ）至今不支持TLS加密传输。

服务端之间的传输，没有地方公开服务端口，因此大家均遵循 RFC2476使用25端口。没有哪家邮箱公司使用非25端口，非25端口其他服务器根本不知道从哪找你的端口定义，根本不知道怎么和你通讯。

此外，服务端之间的通信由于不被用户感知，厂商根本就没兴趣维护，比如搜狐这类，连TLS都没有支持，根本就没考虑安全问题。

综上，25端口是必须的，如果你不使用25端口，那你根本就没法收信。最后强调下为什么我不直接用465端口，这是我不用吗，我又没能力去让Google、微软、网易、腾讯等等一票大公司一起支持使用465传输啊，市面上所有服务端都是用25端口，不用25端口根本连不通啊

**Comment by Jinnrry** [comment]
再补充一下，一封邮件是如何传输的。假设你登录Google GMail的邮箱，向xxxx@qq.com发送了一封邮件。
1、Google服务器收到你的邮件请求，校验你的登陆账号密码、权限啥的
2、解析你的发件地址，找到收件域名，也就是qq.com
3、查询DNS MX记录，找到QQ邮箱服务器的ip地址
4、使用25端口和QQ邮箱服务器的ip地址建了TCP连接
5、发送HELLO等命令，确定通信正常后发送STARTTLS命令，提升到TLS传输
6、传输邮件内容
7、关闭连接

**Comment by T-bagwell** [comment]
> 现目前，互联网上所有的电子邮件，均使用SMTP协议进行传输，SMTP协议和HTTP协议一样，在设计之初并没有考虑到安全性，都是明文传输。后来为了传输安全，在SMTP协议的基础上引入了TLS加密。TLS加密有2种方案： 1、SMTP over TLS，也就是SMTPS协议，类似HTTPS，从握手阶段就进行TLS相关加密 2、SMTP + STARTTLS， 握手阶段+HELLO阶段使用明文传输，准备交换信件内容的时候发送STARTLS命令，后续传输使用TLS加密
> 
> 这两种方案是目前邮件传输过程中保证安全的唯二方案。而其中SMTP over TLS方案使用的端口一般是465，而SMTP+STARTLS使用端口是25
> 
> 回到能不能只用465的问题，这里得分2种情况来说。
> 
> 1、用户使用的邮箱客户端（比如MAC OS的“邮件”、Windos的“电子邮件”、已及其他邮箱APP应用），这些客户端程序基本上都是适配了上述两种传输方式的，而且端口都是可以自定义的，也就是说随便服务端是什么端口，是25还是465还是123还是125，根本没影响，爱是多少是多少
> 
> 2、邮箱服务器和服务器之间的通信（比如PMail服务器和Gmail服务器、GMail和OutLook服务器）。服务端之间的通信，截止目前（2024年），我测试过的主流邮箱服务端，90%都是仅支持SMTP+STARTLS加密方式的。甚至部分服务端（比如搜狐 #72 ）至今不支持TLS加密传输。
> 
> 服务端之间的传输，没有地方公开服务端口，因此大家均遵循 RFC2476使用25端口。没有哪家邮箱公司使用非25端口，非25端口其他服务器根本不知道从哪找你的端口定义，根本不知道怎么和你通讯。
> 
> 此外，服务端之间的通信由于不被用户感知，厂商根本就没兴趣维护，比如搜狐这类，连TLS都没有支持，根本就没考虑安全问题。
> 
> 综上，25端口是必须的，如果你不使用25端口，那你根本就没法收信。最后强调下为什么我不直接用465端口，这是我不用吗，我又没能力去让Google、微软、网易、腾讯等等一票大公司一起支持使用465传输啊，市面上所有服务端都是用25端口，不用25端口根本连不通啊

是不是我可以这么理解：
1. 云服务器封了25端口，也就是说不可能使用云服务器搭建邮件服务器了
2. 我如果想建一个个人的邮件服务器，需要选择不封禁25端口的机房

**Comment by Jinnrry** [comment]
> > 现目前，互联网上所有的电子邮件，均使用SMTP协议进行传输，SMTP协议和HTTP协议一样，在设计之初并没有考虑到安全性，都是明文传输。后来为了传输安全，在SMTP协议的基础上引入了TLS加密。TLS加密有2种方案： 1、SMTP over TLS，也就是SMTPS协议，类似HTTPS，从握手阶段就进行TLS相关加密 2、SMTP + STARTTLS， 握手阶段+HELLO阶段使用明文传输，准备交换信件内容的时候发送STARTLS命令，后续传输使用TLS加密
> > 这两种方案是目前邮件传输过程中保证安全的唯二方案。而其中SMTP over TLS方案使用的端口一般是465，而SMTP+STARTLS使用端口是25
> > 回到能不能只用465的问题，这里得分2种情况来说。
> > 1、用户使用的邮箱客户端（比如MAC OS的“邮件”、Windos的“电子邮件”、已及其他邮箱APP应用），这些客户端程序基本上都是适配了上述两种传输方式的，而且端口都是可以自定义的，也就是说随便服务端是什么端口，是25还是465还是123还是125，根本没影响，爱是多少是多少
> > 2、邮箱服务器和服务器之间的通信（比如PMail服务器和Gmail服务器、GMail和OutLook服务器）。服务端之间的通信，截止目前（2024年），我测试过的主流邮箱服务端，90%都是仅支持SMTP+STARTLS加密方式的。甚至部分服务端（比如搜狐 #72 ）至今不支持TLS加密传输。
> > 服务端之间的传输，没有地方公开服务端口，因此大家均遵循 RFC2476使用25端口。没有哪家邮箱公司使用非25端口，非25端口其他服务器根本不知道从哪找你的端口定义，根本不知道怎么和你通讯。
> > 此外，服务端之间的通信由于不被用户感知，厂商根本就没兴趣维护，比如搜狐这类，连TLS都没有支持，根本就没考虑安全问题。
> > 综上，25端口是必须的，如果你不使用25端口，那你根本就没法收信。最后强调下为什么我不直接用465端口，这是我不用吗，我又没能力去让Google、微软、网易、腾讯等等一票大公司一起支持使用465传输啊，市面上所有服务端都是用25端口，不用25端口根本连不通啊
> 
> 是不是我可以这么理解：
> 
> 1. 云服务器封了25端口，也就是说不可能使用云服务器搭建邮件服务器了
> 2. 我如果想建一个个人的邮件服务器，需要选择不封禁25端口的机房

是的。云服务商封25端口就是为了防止你搭建邮箱服务，担心你搭邮件服务器往外发垃圾邮件对云服务商造成影响。既然本来就是为了禁止你搭邮件服务，即使465端口可以用来收发邮件，云服务商无非就是封禁端口里面加一条465就行了。想尽各种办法绕开云服务商的封禁根本没任何意义。

而且我上面也说了，服务器之间的通信有一部分是明文传输的，即使有一天可以不用25，不用465这些固定端口，如果云服务想彻底封禁邮箱服务，他完全可以监测你的流量特征，单独封掉你的SMTP协议流量。

因此自建邮箱服务最好是买服务器前，先问一问客服，是否可以用于搭建邮箱服务

**Comment by 94zuocom** [comment]
> > > 现目前，互联网上所有的电子邮件，均使用SMTP协议进行传输，SMTP协议和HTTP协议一样，在设计之初并没有考虑到安全性，都是明文传输。后来为了传输安全，在SMTP协议的基础上引入了TLS加密。TLS加密有2种方案： 1、SMTP over TLS，也就是SMTPS协议，类似HTTPS，从握手阶段就进行TLS相关加密 2、SMTP + STARTTLS， 握手阶段+HELLO阶段使用明文传输，准备交换信件内容的时候发送STARTLS命令，后续传输使用TLS加密
> > > 这两种方案是目前邮件传输过程中保证安全的唯二方案。而其中SMTP over TLS方案使用的端口一般是465，而SMTP+STARTLS使用端口是25
> > > 回到能不能只用465的问题，这里得分2种情况来说。
> > > 1、用户使用的邮箱客户端（比如MAC OS的“邮件”、Windos的“电子邮件”、已及其他邮箱APP应用），这些客户端程序基本上都是适配了上述两种传输方式的，而且端口都是可以自定义的，也就是说随便服务端是什么端口，是25还是465还是123还是125，根本没影响，爱是多少是多少
> > > 2、邮箱服务器和服务器之间的通信（比如PMail服务器和Gmail服务器、GMail和OutLook服务器）。服务端之间的通信，截止目前（2024年），我测试过的主流邮箱服务端，90%都是仅支持SMTP+STARTLS加密方式的。甚至部分服务端（比如搜狐 #72 ）至今不支持TLS加密传输。
> > > 服务端之间的传输，没有地方公开服务端口，因此大家均遵循 RFC2476使用25端口。没有哪家邮箱公司使用非25端口，非25端口其他服务器根本不知道从哪找你的端口定义，根本不知道怎么和你通讯。
> > > 此外，服务端之间的通信由于不被用户感知，厂商根本就没兴趣维护，比如搜狐这类，连TLS都没有支持，根本就没考虑安全问题。
> > > 综上，25端口是必须的，如果你不使用25端口，那你根本就没法收信。最后强调下为什么我不直接用465端口，这是我不用吗，我又没能力去让Google、微软、网易、腾讯等等一票大公司一起支持使用465传输啊，市面上所有服务端都是用25端口，不用25端口根本连不通啊
> > 
> > 是不是我可以这么理解：
> > 
> > 1. 云服务器封了25端口，也就是说不可能使用云服务器搭建邮件服务器了
> > 2. 我如果想建一个个人的邮件服务器，需要选择不封禁25端口的机房
> 
> 是的。云服务商封25端口就是为了防止你搭建邮箱服务，担心你搭邮件服务器往外发垃圾邮件对云服务商造成影响。既然本来就是为了禁止你搭邮件服务，即使465端口可以用来收发邮件，云服务商无非就是封禁端口里面加一条465就行了。想尽各种办法绕开云服务商的封禁根本没任何意义。
> 
> 而且我上面也说了，服务器之间的通信有一部分是明文传输的，即使有一天可以不用25，不用465这些固定端口，如果云服务想彻底封禁邮箱服务，他完全可以监测你的流量特征，单独封掉你的SMTP协议流量。
> 
> 因此自建邮箱服务最好是买服务器前，先问一问客服，是否可以用于搭建邮箱服务

阿里云的回复是建议465端口，故不反对，465端口发邮件的。而且大部分云服务器都支持这种设置但是禁了25，我觉得至少应该给个选项

**Comment by cod1ingcoding** [comment]
> 这两种方案是目前邮件传输过程中保证安全的唯二方案。而其中SMTP over TLS方案使用的端口一般是465，而SMTP+STARTLS使用端口是25

还有587端口，这个是目前推荐的STARTTLS端口，这也是目前主流推荐的端口
为了防止被防火墙过滤，其实有的邮件服务商还有2525备用端口，参考：[应该使用哪个 SMTP 端口 | cloudflare](https://www.cloudflare.com/zh-cn/learning/email-security/smtp-port-25-587/)

**Comment by laoma2053** [comment]
> > > 现目前，互联网上所有的电子邮件，均使用SMTP协议进行传输，SMTP协议和HTTP协议一样，在设计之初并没有考虑到安全性，都是明文传输。后来为了传输安全，在SMTP协议的基础上引入了TLS加密。TLS加密有2种方案： 1、SMTP over TLS，也就是SMTPS协议，类似HTTPS，从握手阶段就进行TLS相关加密 2、SMTP + STARTTLS， 握手阶段+HELLO阶段使用明文传输，准备交换信件内容的时候发送STARTLS命令，后续传输使用TLS加密
> > > 这两种方案是目前邮件传输过程中保证安全的唯二方案。而其中SMTP over TLS方案使用的端口一般是465，而SMTP+STARTLS使用端口是25
> > > 回到能不能只用465的问题，这里得分2种情况来说。
> > > 1、用户使用的邮箱客户端（比如MAC OS的“邮件”、Windos的“电子邮件”、已及其他邮箱APP应用），这些客户端程序基本上都是适配了上述两种传输方式的，而且端口都是可以自定义的，也就是说随便服务端是什么端口，是25还是465还是123还是125，根本没影响，爱是多少是多少
> > > 2、邮箱服务器和服务器之间的通信（比如PMail服务器和Gmail服务器、GMail和OutLook服务器）。服务端之间的通信，截止目前（2024年），我测试过的主流邮箱服务端，90%都是仅支持SMTP+STARTLS加密方式的。甚至部分服务端（比如搜狐 #72 ）至今不支持TLS加密传输。
> > > 服务端之间的传输，没有地方公开服务端口，因此大家均遵循 RFC2476使用25端口。没有哪家邮箱公司使用非25端口，非25端口其他服务器根本不知道从哪找你的端口定义，根本不知道怎么和你通讯。
> > > 此外，服务端之间的通信由于不被用户感知，厂商根本就没兴趣维护，比如搜狐这类，连TLS都没有支持，根本就没考虑安全问题。
> > > 综上，25端口是必须的，如果你不使用25端口，那你根本就没法收信。最后强调下为什么我不直接用465端口，这是我不用吗，我又没能力去让Google、微软、网易、腾讯等等一票大公司一起支持使用465传输啊，市面上所有服务端都是用25端口，不用25端口根本连不通啊
> > 
> > 
> > 是不是我可以这么理解：
> > 
> > 1. 云服务器封了25端口，也就是说不可能使用云服务器搭建邮件服务器了
> > 2. 我如果想建一个个人的邮件服务器，需要选择不封禁25端口的机房
> 
> 是的。云服务商封25端口就是为了防止你搭建邮箱服务，担心你搭邮件服务器往外发垃圾邮件对云服务商造成影响。既然本来就是为了禁止你搭邮件服务，即使465端口可以用来收发邮件，云服务商无非就是封禁端口里面加一条465就行了。想尽各种办法绕开云服务商的封禁根本没任何意义。
> 
> 而且我上面也说了，服务器之间的通信有一部分是明文传输的，即使有一天可以不用25，不用465这些固定端口，如果云服务想彻底封禁邮箱服务，他完全可以监测你的流量特征，单独封掉你的SMTP协议流量。
> 
> 因此自建邮箱服务最好是买服务器前，先问一问客服，是否可以用于搭建邮箱服务

能推荐一个可以搭建邮箱服务器的云服务器主机吗？谢谢

**Comment by Jinnrry** [comment]
> > 这两种方案是目前邮件传输过程中保证安全的唯二方案。而其中SMTP over TLS方案使用的端口一般是465，而SMTP+STARTLS使用端口是25
> 
> ### 补充两点：
> 1. 除了25端口可以用来发送STARTTLS，还有587端口，这个是目前推荐的STARTTLS端口，这也是目前很多MTA的主流配置
> 2. 为了防止被防火墙过滤，其实有的邮件服务商还有2525备用端口，比如`telnet smtp.gmail.com 2525`就能通信。
> 
> ### 参考：
> [应该使用哪个 SMTP 端口 | cloudflare](https://www.cloudflare.com/zh-cn/learning/email-security/smtp-port-25-587/)

这些端口的使用场景仅限于客户端和服务端通信。我实测过所有主流邮箱（gmali、outlook、网易、腾讯），服务端通信的时候都只会使用25端口通讯，如果对方探测到25端口不通，直接就丢弃了，不会换端口发信。

**Comment by Jinnrry** [comment]
> > > > 现目前，互联网上所有的电子邮件，均使用SMTP协议进行传输，SMTP协议和HTTP协议一样，在设计之初并没有考虑到安全性，都是明文传输。后来为了传输安全，在SMTP协议的基础上引入了TLS加密。TLS加密有2种方案： 1、SMTP over TLS，也就是SMTPS协议，类似HTTPS，从握手阶段就进行TLS相关加密 2、SMTP + STARTTLS， 握手阶段+HELLO阶段使用明文传输，准备交换信件内容的时候发送STARTLS命令，后续传输使用TLS加密
> > > > 这两种方案是目前邮件传输过程中保证安全的唯二方案。而其中SMTP over TLS方案使用的端口一般是465，而SMTP+STARTLS使用端口是25
> > > > 回到能不能只用465的问题，这里得分2种情况来说。
> > > > 1、用户使用的邮箱客户端（比如MAC OS的“邮件”、Windos的“电子邮件”、已及其他邮箱APP应用），这些客户端程序基本上都是适配了上述两种传输方式的，而且端口都是可以自定义的，也就是说随便服务端是什么端口，是25还是465还是123还是125，根本没影响，爱是多少是多少
> > > > 2、邮箱服务器和服务器之间的通信（比如PMail服务器和Gmail服务器、GMail和OutLook服务器）。服务端之间的通信，截止目前（2024年），我测试过的主流邮箱服务端，90%都是仅支持SMTP+STARTLS加密方式的。甚至部分服务端（比如搜狐 #72 ）至今不支持TLS加密传输。
> > > > 服务端之间的传输，没有地方公开服务端口，因此大家均遵循 RFC2476使用25端口。没有哪家邮箱公司使用非25端口，非25端口其他服务器根本不知道从哪找你的端口定义，根本不知道怎么和你通讯。
> > > > 此外，服务端之间的通信由于不被用户感知，厂商根本就没兴趣维护，比如搜狐这类，连TLS都没有支持，根本就没考虑安全问题。
> > > > 综上，25端口是必须的，如果你不使用25端口，那你根本就没法收信。最后强调下为什么我不直接用465端口，这是我不用吗，我又没能力去让Google、微软、网易、腾讯等等一票大公司一起支持使用465传输啊，市面上所有服务端都是用25端口，不用25端口根本连不通啊
> > > 
> > > 
> > > 是不是我可以这么理解：
> > > 
> > > 1. 云服务器封了25端口，也就是说不可能使用云服务器搭建邮件服务器了
> > > 2. 我如果想建一个个人的邮件服务器，需要选择不封禁25端口的机房
> > 
> > 
> > 是的。云服务商封25端口就是为了防止你搭建邮箱服务，担心你搭邮件服务器往外发垃圾邮件对云服务商造成影响。既然本来就是为了禁止你搭邮件服务，即使465端口可以用来收发邮件，云服务商无非就是封禁端口里面加一条465就行了。想尽各种办法绕开云服务商的封禁根本没任何意义。
> > 而且我上面也说了，服务器之间的通信有一部分是明文传输的，即使有一天可以不用25，不用465这些固定端口，如果云服务想彻底封禁邮箱服务，他完全可以监测你的流量特征，单独封掉你的SMTP协议流量。
> > 因此自建邮箱服务最好是买服务器前，先问一问客服，是否可以用于搭建邮箱服务
> 
> 能推荐一个可以搭建邮箱服务器的云服务器主机吗？谢谢

我用的搬瓦工，没有封25端口，但是也有限制，如果大量发件（每秒几百封这种吧）会被封ip

**Comment by huajiba** [comment]
可以用，腾讯云也是禁25端口。能正常收发，也能第三方发送邮件。发送会被标红，猜测是ssl证书问题(不清楚)
