### ISSUE TITLE
可以收件但无法发送邮件

### ISSUE THREAD

**Issue by RichardMiku** [Jinnrry/PMail#131]
## 请完整读完[README](https://github.com/Jinnrry/PMail/blob/master/README_CN.md)再提问! / Before asking questions, please read the [README](https://github.com/Jinnrry/PMail/blob/master/README.md) !

我可以收到来自我QQ邮箱的邮件，但是我无法发送到我的QQ邮箱，我想问一下这个是什么情况？

**Comment by Jinnrry** [comment]
发信日志？

**Comment by RichardMiku** [comment]
我点发送的时候显示发送成功，我查询了一下那个屏蔽，可能是因为我今天才注册的域名，明天再试试

**Comment by Jinnrry** [comment]
https://www.mail-tester.com/

在这里测试下你的邮箱服务，看下spf、dkim、还有ip反查这些是否都正确配置了

**Comment by RichardMiku** [comment]
那些配置全都能验到正常，也许是域名没过保护器，这是一个刚买的域名

![image](https://github.com/Jinnrry/PMail/assets/44936304/331d6f43-9e2d-48f9-93c3-d0e2ead53325)

**Comment by Jinnrry** [comment]
QQ邮箱有个"自助查询"，你查看看是不是被系统拦截了。

新域名、xyz域名，这简直就差把垃圾邮件写脑门上了。

目测大概率不可能解封，搭邮箱还是用com.cn这类域名吧，xyz 基本上都是黑灰产以及垃圾邮件，被封禁太正常了
