### ISSUE TITLE
Aws 服务器搭建 PMail 邮箱服务时，Router53域名配置时 HostName 为 “-”时需要如何处理？

### ISSUE THREAD

**Issue by jackyglony** [Jinnrry/PMail#133]
![1718612165483](https://github.com/Jinnrry/PMail/assets/2222041/14698e1f-b11c-4c6c-9c53-7aac48634cae)

**Comment by Jinnrry** [comment]
Emmm，这个“-”的意思是留空，不填，不是说要填一个“-“

**Comment by feizhuqwq** [comment]
![image](https://github.com/Jinnrry/PMail/assets/78783893/7a10d265-bc4b-40b6-97a0-d8821c9411c4)
![image](https://github.com/Jinnrry/PMail/assets/78783893/f2793d4a-8c52-46fc-8144-84c99733cdc8)
