### ISSUE TITLE
SSL证书申请哪个域名?

### ISSUE THREAD

**Issue by jainnieh** [Jinnrry/PMail#137]
自己尝试手动配SSL, 配了个www.example.com的证书, 打开管理界面浏览器提醒not secure.

手动配SSL证书, 申请哪个域名的证书?
我是阿里云免费的单域名证书. 每次只能申请一个单域名, 比如www.example.com, 这个证书对aaa.example.com无效, 所以我想知道具体申请哪一个配进来?

使用自动获取证书的方式暂时没有出现问题.

**Comment by Jinnrry** [comment]
根域名、pop、smtp

**Comment by jainnieh** [comment]
3个怎么放到一个public或private文件中

**Comment by jainnieh** [comment]
不知道你是不是用的cloudfare, cf可以申请通配符, 也就是一个证书可以给多个三级域名用

**Comment by zivmax** [comment]
> 3个怎么放到一个public或private文件中

直接拼接放在 `public.crt` 和 `private.key`
