### ISSUE TITLE
wechat模块报错 [wechat_push_linux_amd64] Plugin Start! PID:3925panic: open ../../config/config.json: no such file or directory

### ISSUE THREAD

**Issue by 94zuocom** [Jinnrry/PMail#139]
[info][2024-06-28 17:46:25][/home/runner/work/PMail/PMail/server/http_server/setup_server.go:71]Setup End!
[info][2024-06-28 17:46:25][/home/runner/work/PMail/PMail/server/hooks/base.go:179][telegram_push_linux_amd64] Plugin Load
[telegram_push_linux_amd64] Plugin Start! PID:3902[info][2024-06-28 17:46:26][/home/runner/work/PMail/PMail/server/hooks/base.go:211][telegram_push_linux_amd64] Plugin Load Success!
[info][2024-06-28 17:46:26][/home/runner/work/PMail/PMail/server/hooks/base.go:179][web_push_linux_amd64] Plugin Load
[web_push_linux_amd64] Plugin Start! PID:3910[info][2024-06-28 17:46:27][/home/runner/work/PMail/PMail/server/hooks/base.go:211][web_push_linux_amd64] Plugin Load Success!
[info][2024-06-28 17:46:27][/home/runner/work/PMail/PMail/server/hooks/base.go:179][wechat_push_linux_amd64] Plugin Load
[wechat_push_linux_amd64] Plugin Start! PID:3925panic: open ../../config/config.json: no such file or directory

goroutine 1 [running]:
main.NewWechatPushHook()
        /home/runner/work/PMail/PMail/server/hooks/wechat_push/wechat_push.go:137 +0x27f
main.main()
        /home/runner/work/PMail/PMail/server/hooks/wechat_push/wechat_push.go:187 +0x13
[error][2024-06-28 17:46:27][/home/runner/work/PMail/PMail/server/hooks/base.go:195][wechat_push_linux_amd64] Plugin Stop. Error:<nil> Stat:exit status 2
[error][2024-06-28 17:46:32][/home/runner/work/PMail/PMail/server/hooks/base.go:206][wechat_push_linux_amd64] Start Fail!

**Comment by 94zuocom** [comment]
config.json如下
{
    "logLevel": "",
    "domain": "*************.com",
    "domains": null,
    "webDomain": "************",
    "dkimPrivateKeyPath": "config/dkim/dkim.priv",
    "sslType": "1",
    "SSLPrivateKeyPath": "./config/ssl/private.key",
    "SSLPublicKeyPath": "./config/ssl/public.crt",
    "dbDSN": "./config/pmail.db",
    "dbType": "sqlite",
    "httpsEnabled": 2,
    "spamFilterLevel": 0,
    "httpPort": 0,
    "httpsPort": 0,
    "weChatPushAppId": "",
    "weChatPushSecret": "",
    "weChatPushTemplateId": "",
    "weChatPushUserId": "",
    "tgBotToken": "",
    "tgChatId": "",
    "isInit": true,
    "webPushUrl": "",
    "webPushToken": ""
}

**Comment by Jinnrry** [comment]
v2.5版本修复

**Comment by 94zuocom** [comment]
> v2.5版本修复

现在要装怎么绕过去

**Comment by Jinnrry** [comment]
把wechat插件的二进制文件删了，或者copy一份配置文件到 ../../config/config.json
