### ISSUE TITLE
向GMAIL发邮件，为什么默认走的是25号端口而不是465，是配置问题还是BUG

### ISSUE THREAD

**Issue by 94zuocom** [Jinnrry/PMail#140]
![image](https://github.com/Jinnrry/PMail/assets/19161243/4a893f4e-26f1-46fe-b2c6-013d29f2385f)

**Comment by 94zuocom** [comment]
为什么提出这个问题：因为阿里云默认是关掉25的
![image](https://github.com/Jinnrry/PMail/assets/19161243/d0eae5f6-31f8-4038-bc77-28b0c7b3f082)

**Comment by Jinnrry** [comment]
#130

**Comment by 94zuocom** [comment]
> #130

那个文档issue我看了 ，但是问题是web端用的就是25
