### ISSUE TITLE
关于docker里的证书配置

### ISSUE THREAD

**Issue by 0ui0** [Jinnrry/PMail#142]
我使用1panel面板，在不使用80端口，然后希望用nginx反向代理到容器里的9080端口，结果发现卡在证书环节
1. 自动配置证书无法成功配置
2. 改为手动配置后，发现无法访问后台页面，提示ERR_SSL_PROTOCOL_ERROR
想问下能不能不要在安装阶段强制配置证书，进到后台里再配置？证书是否配置正确对能否进入 管理页面应该是没有影响的

**Comment by Jinnrry** [comment]
下个版本支持

**Comment by Jinnrry** [comment]
现在可以手动改配置文件，改完再重启。
