### ISSUE TITLE
无法查看邮件

### ISSUE THREAD

**Issue by dongchenxuan** [Jinnrry/PMail#144]
## 请完整读完[README](https://github.com/Jinnrry/PMail/blob/master/README_CN.md)再提问! / Before asking questions, please read the [README](https://github.com/Jinnrry/PMail/blob/master/README.md) !

**请说明问题 / Describe the bug**
查看收件箱中的邮件，页面内容为空

**如何复现 / To Reproduce**
1. 点击左侧菜单栏中的收件箱
2. 点击任意一封邮件
3. 出现空页面

**日志信息 / Log**
[error][2024-07-04 16:51:00][0a00040266866274f5a5dc4f448c33b0][/home/runner/work/PMail/PMail/server/services/detail/detail.go:32]SQL error:Error 1054 (42S22): Unknown column 'is_read' in 'field list'

**Comment by 0ui0** [comment]
同问题，我也遇到了

**Comment by cod1ingcoding** [comment]
这个貌似是email表里没有is_read字段，但是其他地方（比如列表页）好像又是读的user_email里的is_read字段。

**Comment by Jinnrry** [comment]
确实是is_read字段的问题，v2.5.0重新设计了数据表，单测用例没覆盖到。今晚回去改改，明天发个新版
