### ISSUE TITLE
DNS记录申请SSL证书逻辑有问题？

### ISSUE THREAD

**Issue by chaohua27** [Jinnrry/PMail#146]
既然是开局设置由DNS记录申请SSL证书，./config/ssl/下本来就不会有private.key文件吧？
![20240706220614](https://github.com/Jinnrry/PMail/assets/33476686/41f30112-0796-4e72-a5b9-b11d3f81c4c8)

**Comment by Jinnrry** [comment]
v.2.5.3 修复了
