### ISSUE TITLE
DNS设置：这一步设置好点下一步提示：stat ./config/ssl/private.key: no such file or directory

### ISSUE THREAD

**Issue by laoma2053** [Jinnrry/PMail#149]
## 请完整读完[README](https://github.com/Jinnrry/PMail/blob/master/README_CN.md)再提问! / Before asking questions, please read the [README](https://github.com/Jinnrry/PMail/blob/master/README.md) !

**请说明问题 / Describe the bug**
DNS设置：这一步设置好点下一步提示：stat ./config/ssl/private.key: no such file or directory
![image](https://github.com/Jinnrry/PMail/assets/169715751/0c0eaf90-8d0c-47f9-94ee-f8e77ae14473)

按文档步骤安装后出现如下问题

**Comment by Jinnrry** [comment]
v.2.5.3 修复了

**Comment by Jinnrry** [comment]
用docker安装的还是下载文件安装的？下载文件安装的话你重新下一个就行了

**Comment by laoma2053** [comment]
docker安装的，重新安装了一次。问题解决了，感谢你~
现在提醒我域名未备案，等待域名备案成功
