### ISSUE TITLE
init了两个hook的话会触发两次重复的

### ISSUE THREAD

**Issue by J3n5en** [Jinnrry/PMail#15]
```
async.New(nil).Process(func() {
    hook.ReceiveParseAfter(email)
})
```

看起来会导致触发最后的一个hook  x次，而跳过前面的hook，不清楚要怎么处理，有空麻烦处理一下，谢谢。

**Comment by Jinnrry** [comment]
嗯，确实有问题，hook是异步执行的，写代码的时候没注意。

https://github.com/Jinnrry/PMail/tree/hotfix-async

看下这个分支的代码还有问题不

Diff : https://github.com/Jinnrry/PMail/pull/16
