### ISSUE TITLE
请问如何设置PMail和nginx reverse proxy?

### ISSUE THREAD

**Issue by Yeeler** [Jinnrry/PMail#151]

**Comment by Jinnrry** [comment]
请描述你遇到的问题

**Comment by Yeeler** [comment]
多谢 大佬的这个项目。
以下是我的配置文件，已经成功安装。 我用nginx反向代理80端口，证书也是安装在nginx上。做了发件测试。认证有问题，我需要如何手动生成证书 或者 可以拷贝 certbot为nginx创建的证书？

{
  "logLevel": "info", //log output level
  "domain": "domain.com", // Your domain
  "webDomain": "mail.domain.com", // web domain
  "dkimPrivateKeyPath": "config/dkim/dkim.priv", // dkim key path
  "sslType": "1", // ssl certificate update mode, 0 automatic, 1 manual
  "SSLPrivateKeyPath": "config/ssl/private.key", // ssl certificate path
  "SSLPublicKeyPath": "config/ssl/public.crt", // ssl certificate path
  "dbDSN": "./config/pmail.db", // database connect DSN
  "dbType": "sqlite", //database type ，`sqlite` or `mysql`
  "httpsEnabled": 0, // enabled https , 0:enabled 1:enablde 2:disenabled
  "httpPort": 80, // http port . default 80
  "httpsPort": 443, // https port . default 443
  "spamFilterLevel": 0,// Spam filter level, 0: no filter, 1: filtering when `spf` and `dkim` don't pass, 2: filtering when `spf` don't pass
  "isInit": false // If false, it will enter the bootstrap process.
}

![screencapture-mail-tester-test-p9jm5wjse-reloaded-1-2024-07-10-13_20_37](https://github.com/Jinnrry/PMail/assets/5031611/6f668bc6-d30b-43d1-b700-44582289c31f)

**Comment by Jinnrry** [comment]
1、nginx管理证书的话把httpsEnabled设置成2
2、dkim错误，你dns没有设置dkim密钥吧

**Comment by Yeeler** [comment]
之前mx记录弄错了  现在出现了timeout

yeeler@origin:~/PMail/server$ docker compose up
WARN[0000] /home/yeeler/PMail/server/docker-compose.yml: `version` is obsolete 
[+] Running 1/0
 ✔ Container server-pmail-1  Created                                                                                                                                                                                     0.0s 
Attaching to pmail-1
pmail-1  | [info][2024-07-10 21:26:42][/work/main.go:81]*******************************************************************
pmail-1  | [info][2024-07-10 21:26:42][/work/main.go:82]***	Server Start Success 
pmail-1  | 
pmail-1  | [info][2024-07-10 21:26:42][/work/main.go:83]***	Server Version: v2.5.3 
pmail-1  | 
pmail-1  | [info][2024-07-10 21:26:42][/work/main.go:84]***	Git Commit Hash: 402e00150d97f2293b9065319ef8aedd3b09a900 
pmail-1  | [info][2024-07-10 21:26:42][/work/main.go:85]***	Build Date: 2024-07-08 16:49:03 
pmail-1  | [info][2024-07-10 21:26:42][/work/main.go:86]***	Build GoLang Version: go version go1.22.5 linux/amd64 
pmail-1  | [info][2024-07-10 21:26:42][/work/main.go:87]*******************************************************************
pmail-1  | [info][2024-07-10 21:26:42][/work/hooks/base.go:181][telegram_push] Plugin Load
pmail-1  | [telegram_push] Plugin Start! PID:12[info][2024-07-10 21:26:43][/work/hooks/base.go:213][telegram_push] Plugin Load Success!
pmail-1  | [info][2024-07-10 21:26:43][/work/hooks/base.go:181][web_push] Plugin Load
pmail-1  | [web_push] Plugin Start! PID:16[info][2024-07-10 21:26:44][/work/hooks/base.go:213][web_push] Plugin Load Success!
pmail-1  | [info][2024-07-10 21:26:44][/work/hooks/base.go:181][wechat_push] Plugin Load
pmail-1  | [wechat_push] Plugin Start! PID:21[info][2024-07-10 21:26:45][/work/hooks/base.go:213][wechat_push] Plugin Load Success!
pmail-1  | [warning][2024-07-10 21:26:45][/work/res_init/init.go:52]Config File Info:  {"logLevel":"debug","domain":"aaa.com","domains":["aaa.com"],"webDomain":"email.aaa.com","dkimPrivateKeyPath":"config/dkim/dkim.priv","sslType":"1","SSLPrivateKeyPath":"./config/ssl/private.key","SSLPublicKeyPath":"./config/ssl/public.crt","dbDSN":"./config/pmail_temp.db","dbType":"sqlite","httpsEnabled":2,"spamFilterLevel":0,"httpPort":80,"httpsPort":443,"weChatPushAppId":"","weChatPushSecret":"","weChatPushTemplateId":"","weChatPushUserId":"","tgBotToken":"","tgChatId":"","isInit":true,"webPushUrl":"","webPushToken":""}
pmail-1  | [info][2024-07-10 21:26:45][/work/pop3_server/pop3server.go:27]POP3 With TLS Server Start On Port :995
pmail-1  | [info][2024-07-10 21:26:45][/work/smtp_server/smtp.go:175]Starting Smtp Server Port: :25
pmail-1  | [info][2024-07-10 21:26:45][/work/http_server/http_server.go:80]HttpServer Start On Port :80
pmail-1  | [info][2024-07-10 21:26:45][/work/pop3_server/pop3server.go:46]POP3 Server Start On Port :110
pmail-1  | [info][2024-07-10 21:26:45][/work/smtp_server/smtp.go:147]Starting Smtp With SSL Server Port: :465
pmail-1  | [info][2024-07-10 21:27:09][c0a84002668e8c2d62c700014870dcb0][/work/controllers/email/send.go:57]发送邮件
pmail-1  | [debug][2024-07-10 21:27:09][c0a84002668e8c2d62c700014870dcb0][/work/controllers/email/send.go:152]插件执行--SendBefore
pmail-1  | [debug][2024-07-10 21:27:09][c0a84002668e8c2d62c700014870dcb0][/work/hooks/base.go:50][telegram_push]Plugin SendBefore Start
pmail-1  | [debug][2024-07-10 21:27:09][c0a84002668e8c2d62c700014870dcb0][/work/hooks/base.go:69][telegram_push]Plugin SendBefore End
pmail-1  | [debug][2024-07-10 21:27:09][c0a84002668e8c2d62c700014870dcb0][/work/hooks/base.go:50][web_push]Plugin SendBefore Start
pmail-1  | [debug][2024-07-10 21:27:09][c0a84002668e8c2d62c700014870dcb0][/work/hooks/base.go:69][web_push]Plugin SendBefore End
pmail-1  | [debug][2024-07-10 21:27:09][c0a84002668e8c2d62c700014870dcb0][/work/hooks/base.go:50][wechat_push]Plugin SendBefore Start
pmail-1  | [debug][2024-07-10 21:27:09][c0a84002668e8c2d62c700014870dcb0][/work/hooks/base.go:69][wechat_push]Plugin SendBefore End
pmail-1  | [debug][2024-07-10 21:27:09][c0a84002668e8c2d62c700014870dcb0][/work/controllers/email/send.go:159]插件执行--SendBefore End
pmail-1  | [debug][2024-07-10 21:27:09][c0a84002668e8c2d62c700014870dcb0][/work/utils/send/send.go:126]Message Infos : DKIM-Signature: a=rsa-sha256; bh=LmOUdOOQ1/nljnKoO+A4LqHI/wp0btxn1QU+LJ6q/KM=;
pmail-1  |  c=simple/simple; d=aaa.com;
pmail-1  |  h=Content-Type:Mime-Version:Subject:To:From:Message-Id:Date; s=default;
pmail-1  |  t=1720618029; v=1;
pmail-1  |  b=ajOTutt37JmYyfXot/+WtkQFNwsIjyqgjvVBCy6BeeR4GIj16gSBJUFfOvWtC/urV1Ns1NKF
pmail-1  |  gCkkRknwgLnwGNhszgtgSZfBJ/C+G6QbMpBT3HGpan9zCLP/9dK28Rku3t5QXPffR/l/DhcIP1M
pmail-1  |  wLZ16N5inu8V1rJe6PolC8H0=
pmail-1  | Content-Type: multipart/mixed;
pmail-1  |  boundary=86904f13d11768291e792468b471ea7ca9eaaf80733a3dd90a9da112bb2a
pmail-1  | Mime-Version: 1.0
pmail-1  | Subject: 44444444444
pmail-1  | To: <yeeler@21cn.com>
pmail-1  | From: "admin" <admin@aaa.com>
pmail-1  | Message-Id: <10@aaa.com>
pmail-1  | Date: Wed, 10 Jul 2024 21:27:09 +0800
pmail-1  | 
pmail-1  | --86904f13d11768291e792468b471ea7ca9eaaf80733a3dd90a9da112bb2a
pmail-1  | Content-Type: multipart/alternative;
pmail-1  |  boundary=b49b13e6359823c5cfe3ec38d9e0acc316219598eb38698056dc13a0e64c
pmail-1  | 
pmail-1  | --b49b13e6359823c5cfe3ec38d9e0acc316219598eb38698056dc13a0e64c
pmail-1  | Content-Transfer-Encoding: quoted-printable
pmail-1  | Content-Disposition: inline
pmail-1  | Content-Type: text/plain; charset=UTF-8
pmail-1  | 
pmail-1  | hello
pmail-1  | --b49b13e6359823c5cfe3ec38d9e0acc316219598eb38698056dc13a0e64c
pmail-1  | Content-Transfer-Encoding: quoted-printable
pmail-1  | Content-Disposition: inline
pmail-1  | Content-Type: text/html; charset=UTF-8
pmail-1  | 
pmail-1  | <p>hello</p>
pmail-1  | --b49b13e6359823c5cfe3ec38d9e0acc316219598eb38698056dc13a0e64c--
pmail-1  | 
pmail-1  | --86904f13d11768291e792468b471ea7ca9eaaf80733a3dd90a9da112bb2a--
pmail-1  | 
pmail-1  | [error][2024-07-10 21:27:11][c0a84002668e8c2d62c700014870dcb0][/work/utils/send/send.go:206][0xc0000e3ba0] 邮件投递失败dial tcp 74.125.130.27:25: i/o timeout
pmail-1  | [debug][2024-07-10 21:27:11][c0a84002668e8c2d62c700014870dcb0][/work/controllers/email/send.go:196]插件执行--SendAfter
pmail-1  | [debug][2024-07-10 21:27:11][c0a84002668e8c2d62c700014870dcb0][/work/hooks/base.go:74][wechat_push]Plugin SendAfter Start
pmail-1  | [debug][2024-07-10 21:27:11][c0a84002668e8c2d62c700014870dcb0][/work/hooks/base.go:74][web_push]Plugin SendAfter Start
pmail-1  | [error][2024-07-10 21:27:11][/work/hooks/framework/framework.go:112]params error json: cannot unmarshal object into Go struct field HookDTO.ErrMap of type error
pmail-1  | [error][2024-07-10 21:27:11][/work/hooks/framework/framework.go:112]params error json: cannot unmarshal object into Go struct field HookDTO.ErrMap of type error
pmail-1  | [debug][2024-07-10 21:27:11][c0a84002668e8c2d62c700014870dcb0][/work/hooks/base.go:74][telegram_push]Plugin SendAfter Start
pmail-1  | [error][2024-07-10 21:27:11][/work/hooks/framework/framework.go:112]params error json: cannot unmarshal object into Go struct field HookDTO.ErrMap of type error
pmail-1  | [debug][2024-07-10 21:27:11][c0a84002668e8c2d62c700014870dcb0][/work/hooks/base.go:88][web_push]Plugin SendAfter End
pmail-1  | [debug][2024-07-10 21:27:11][c0a84002668e8c2d62c700014870dcb0][/work/hooks/base.go:88][wechat_push]Plugin SendAfter End
pmail-1  | [debug][2024-07-10 21:27:11][c0a84002668e8c2d62c700014870dcb0][/work/hooks/base.go:88][telegram_push]Plugin SendAfter End
pmail-1  | [debug][2024-07-10 21:27:11][c0a84002668e8c2d62c700014870dcb0][/work/controllers/email/send.go:208]插件执行--SendAfter

**Comment by Jinnrry** [comment]
邮件投递失败dial tcp 94.23.206.89:25: i/o timeout

你服务器被封25端口了吧？阿里云、腾讯云之类的服务器，需要提工单给客户，申请解封25端口

**Comment by Yeeler** [comment]
我用的是家里的宽带 做了端口mapping.  IP一直是变的 用了 dynu 作了动态域名解析。
不知道他们能不能开放 不行就换宽带服务商了。
