### ISSUE TITLE
如果能批量创建账号就完美了

### ISSUE THREAD

**Issue by shidahuilang** [Jinnrry/PMail#152]

**Comment by Jinnrry** [comment]
怎么个批量法？

**Comment by shidahuilang** [comment]
比如绑定的域名邮箱是：mail@domain.com  可以自定义 多个邮箱，mail1@domain.com，mail2@domain.com，公司每人可以分到一个不同的邮箱

**Comment by shidahuilang** [comment]
好像还真可以，牛逼大佬！

**Comment by shidahuilang** [comment]
是不是只要创建不同的管理员账号就可以了

**Comment by shidahuilang** [comment]
大佬管理员账号是不是只能设置一个，其他的账号不能设置管理员权限

**Comment by shidahuilang** [comment]
真好用，iredmail 和宝塔的邮局都没这个好玩，感谢大佬，如果可以设置多个管理员账号就爽歪歪了

**Comment by Jinnrry** [comment]
目前的设定是管理员只能有一个，普通用户随便多少个

**Comment by shidahuilang** [comment]
大佬请教下我用docker搭建的，tg通知不生效，
![image](https://github.com/Jinnrry/PMail/assets/81285256/c41eb313-6579-4b45-aa63-0ebdf4fa70cb)
请问路径有问题吗？还是？

**Comment by shidahuilang** [comment]
![image](https://github.com/Jinnrry/PMail/assets/81285256/1f2113c4-d85d-43ae-9c4d-d89784263b1c)
z这样的格式

**Comment by shidahuilang** [comment]
能不能支持管理员可以设置2个或者3个大佬，这个功能很想要

**Comment by Jinnrry** [comment]
目前没这个计划。

PMail目前多用户的设计是，如果邮箱地址有用户名匹配，邮件就给匹配的账号。如果邮箱地址找不到匹配的用户，邮件就给管理员，如果管理员出现多个，邮件的归属太混乱了，这逻辑不知道怎么设计了

**Comment by shidahuilang** [comment]
好的，理解！再次感谢，大佬！我用网易邮箱大师，可以正常发信和收信，但是点开收到的邮件就会一直提示与邮箱服务器连接失败，不能看邮件的内容！佬遇到过吗？知道什么情况吗

**Comment by shidahuilang** [comment]
![image](https://github.com/user-attachments/assets/2c7d820c-8338-4bc9-b91e-5be9e6171345)
这个问题困扰了几天了，一直没有办法，用IOS自带的邮箱也可以正常发信，会显示正在下载邮件，然后就一个邮件没有下载下来

**Comment by shidahuilang** [comment]
终于搞明白了。苹果手机问题，我用小米手机正常
