### ISSUE TITLE
搭建第六步的ssl证书有一些疑问

### ISSUE THREAD

**Issue by zlose** [Jinnrry/PMail#153]
这个证书是给哪个域名用的，我这边是自上传的证书，没看懂是给哪个域名使用的，如果是pop smtp @这三个域名，为什么只配置一套证书，看了issue和wiki都没找到类似的解答
<img width="806" alt="image" src="https://github.com/Jinnrry/PMail/assets/44944302/14adb530-b597-44b7-93c7-db779090119b">

**Comment by Jinnrry** [comment]
自行了解泛域名证书，一个证书可以签发给多个域名
