### ISSUE TITLE
邮件删除不掉，提示成功，但是还在垃圾箱里面

### ISSUE THREAD

**Issue by shidahuilang** [Jinnrry/PMail#154]
## 请完整读完[README](https://github.com/Jinnrry/PMail/blob/master/README_CN.md)再提问! / Before asking questions, please read the [README](https://github.com/Jinnrry/PMail/blob/master/README.md) !

**请说明问题 / Describe the bug**

**如何复现 / To Reproduce**

**你预期的行为 / Expected behavior**

**贴上你的配置文件 / Program configuration file contents**
<details>
  <summary>config.json</summary>

```
这里贴上你的配置文件内容。
Copy the contents of your configuration file here.
```

</details>

**日志信息 / Log**
<details>
  <summary>log</summary>

```
这里贴上问题相关日志
Copy the contents of your log here.

```
邮件删除不掉，提示成功，但是还在垃圾箱里面
</details>

**Comment by shidahuilang** [comment]
![photo_2024-07-11_14-08-03](https://github.com/Jinnrry/PMail/assets/81285256/baadf807-bed0-4852-a3f8-d8b9cdd58101)
删除提示成功，但是邮件一个不少的还在，删除多次，没有效果，大佬这是什么原因造成的

**Comment by Jinnrry** [comment]
啊。。。因为我只实现了软删除，也就是移动到垃圾箱里面，垃圾箱里面继续删除还是移动到垃圾箱里面

**Comment by Jinnrry** [comment]
下个版本支持垃圾箱里面的删除变成真删除

**Comment by shidahuilang** [comment]
好的

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/PMail/releases/tag/v2.6.0

这个版本修复了

**Comment by shidahuilang** [comment]
好的，感谢大佬！docker 镜像也更新了吗
