### ISSUE TITLE
请问收信规则中如何正确使用正则匹配

### ISSUE THREAD

**Issue by Wait845** [Jinnrry/PMail#156]
## 请完整读完[README](https://github.com/Jinnrry/PMail/blob/master/README_CN.md)再提问! / Before asking questions, please read the [README](https://github.com/Jinnrry/PMail/blob/master/README.md) !

**请说明问题 / Describe the bug**

我的邮箱总是能收到不属于我域名的邮件，我希望能用收信规则，将不属于我域名的邮件删除。但是当我尝试正则匹配方法过滤邮件的时候，似乎不生效

**如何复现 / To Reproduce**
1.新建收信规则
2.创建规则(假设我的域名是abc.com)
以下规则全部满足时：收件人地址 正则匹配 ^(?!.\*abc\\.com).\*
执行操作：移动分组 spam
3.完成上述步骤后，不属于我域名的邮件仍没有正确移动到spam分组

**你预期的行为 / Expected behavior**
根据上述规则，不属于我域名的分组应该移动到spam分组

**Comment by Jinnrry** [comment]
测试了一下，应该是go正则包的问题，go语言的正则包不支持这种语法
```
	res, err := regexp.MatchString("^(?!.*abc\\.com).*", "aa@aa.com")
	fmt.Println(res)
	fmt.Println(err) // error parsing regexp: invalid or unsupported Perl syntax: `(?!`
```

这里有一个讨论，具体怎么解决我也不清楚，我对正则不怎么熟悉。

https://stackoverflow.com/questions/38933898/error-parsing-regexp-invalid-or-unsupported-perl-syntax

**Comment by Jinnrry** [comment]
1、肯定可以
2、下个版本会加一个垃圾邮件过滤插件，使用机器学习进行过滤，使用了rervec模型，在trec06c数据集上训练和测试，可以达到99%的准确度。和目前Google Gmail使用了相同的模型，理论上能够达到GMail的效果

**Comment by Jinnrry** [comment]
最新版改了
