### ISSUE TITLE
aws ec2 服务器上尝试搭建此服务，测试发送到google邮箱失败，其他邮箱也是，以下是日志信息，容器网络测试过没问题，使用的是master分支最新构建镜像

### ISSUE THREAD

**Issue by zouchengli** [Jinnrry/PMail#159]
[info][2024-07-15 17:38:49][ac1700026694ee29b2920001ca0752b0][/work/server/controllers/email/send.go:58]发送邮件
[error][2024-07-15 17:38:51][ac1700026694ee29b2920001ca0752b0][/work/server/utils/send/send.go:209][0xc0002a6160] 邮件投递失败dial tcp 142.251.8.26:25: i/o timeout
[error][2024-07-15 17:38:51][/work/server/hooks/framework/framework.go:112]params error json: cannot unmarshal object into Go struct field HookDTO.ErrMap of type error
[error][2024-07-15 17:38:51][/work/server/hooks/framework/framework.go:112]params error json: cannot unmarshal object into Go struct field HookDTO.ErrMap of type error
[error][2024-07-15 17:38:51][/work/server/hooks/framework/framework.go:112]params error json: cannot unmarshal object into Go struct field HookDTO.ErrMap of type error

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/PMail/issues/160

timeout错误都排查网络问题，timeout与程序无关

**Comment by zouchengli** [comment]
> #160
> 
> timeout错误都排查网络问题，timeout与程序无关

我知道了，我看了一篇文章，说是aws ec2把25出口流量端口关了
https://repost.aws/zh-Hans/knowledge-center/ec2-port-25-throttle
