### ISSUE TITLE
无法收件和发件，邮件投递失败dial tcp 142.251.8.27:25: i/o timeout

### ISSUE THREAD

**Issue by lujia1009** [Jinnrry/PMail#160]
执行：
./pmail_linux_amd64
结果：
[info][2024-07-16 10:54:46][/home/runner/work/PMail/PMail/server/smtp_server/smtp.go:175]Starting Smtp Server Port: :25
[info][2024-07-16 10:54:46][/home/runner/work/PMail/PMail/server/pop3_server/pop3server.go:27]POP3 With TLS Server Start On Port :995
[info][2024-07-16 10:54:46][/home/runner/work/PMail/PMail/server/http_server/http_server.go:80]HttpServer Start On Port :80
[info][2024-07-16 10:54:46][/home/runner/work/PMail/PMail/server/smtp_server/smtp.go:147]Starting Smtp With SSL Server Port: :465
[info][2024-07-16 10:54:46][/home/runner/work/PMail/PMail/server/pop3_server/pop3server.go:46]POP3 Server Start On Port :110

正常启动。

发送邮件出现报错：
[error][2024-07-16 10:56:13][67613a136695e14b17d828b7de369ab0][/home/runner/work/PMail/PMail/server/utils/send/send.go:209][0xc0003da1c0] 邮件投递失败dial tcp 142.251.8.27:25: i/o timeout
[error][2024-07-16 10:56:13][/home/runner/work/PMail/PMail/server/hooks/framework/framework.go:112]params error json: cannot unmarshal object into Go struct field HookDTO.ErrMap of type error
[error][2024-07-16 10:56:13][/home/runner/work/PMail/PMail/server/hooks/framework/framework.go:112]params error json: cannot unmarshal object into Go struct field HookDTO.ErrMap of type error
[error][2024-07-16 10:56:13][/home/runner/work/PMail/PMail/server/hooks/framework/framework.go:112]params error json: cannot unmarshal object into Go struct field HookDTO.ErrMap of type error

主要错误信息：dial tcp 142.251.8.27:25: i/o timeout

出入口的端口全部放行，但是没有用

**Comment by starriesWEB** [comment]
感觉像是云厂商把25的出口流量给关了

**Comment by starriesWEB** [comment]
感觉像是云厂商把25的出口流量给关了

**Comment by lujia1009** [comment]
我服务器端口全部放行了啊

**Comment by lujia1009** [comment]
> 感觉像是云厂商把25的出口流量给关了

我服务器端口全部放行了啊

**Comment by starriesWEB** [comment]
> > 感觉像是云厂商把25的出口流量给关了
> 
> 我服务器端口全部放行了啊

![1721105961906](https://github.com/user-attachments/assets/0aa53c74-191e-4e58-9592-0d288d484f57)
要申请的，安全组开了没用

**Comment by lujia1009** [comment]
> > > 感觉像是云厂商把25的出口流量给关了
> > 
> > 
> > 我服务器端口全部放行了啊
> 
> ![1721105961906](https://private-user-images.githubusercontent.com/73122677/348946093-0aa53c74-191e-4e58-9592-0d288d484f57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTkwNDMsIm5iZiI6MTcyMTExODc0MywicGF0aCI6Ii83MzEyMjY3Ny8zNDg5NDYwOTMtMGFhNTNjNzQtMTkxZS00ZTU4LTk1OTItMGQyODhkNDg0ZjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA4MzIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmOTI5NGRiZWVlYjg2N2E0MzM1NmRjNTQ4ODdlZjQ1NjIyOGExMzVhMDg1NGM1MDBiNDI1MjhjYjg0ODc4MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XDo3q3qiEr8IMgKvIlqEuP0V0Iq8uh8txie5getKfCE) 要申请的，安全组开了没用

安全组肯定有开呀，又不是没有这个常识，我已经放弃了。使用其它的了

**Comment by lujia1009** [comment]
> > > 感觉像是云厂商把25的出口流量给关了
> > 
> > 
> > 我服务器端口全部放行了啊
> 
> ![1721105961906](https://private-user-images.githubusercontent.com/73122677/348946093-0aa53c74-191e-4e58-9592-0d288d484f57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExODAzMDAsIm5iZiI6MTcyMTE4MDAwMCwicGF0aCI6Ii83MzEyMjY3Ny8zNDg5NDYwOTMtMGFhNTNjNzQtMTkxZS00ZTU4LTk1OTItMGQyODhkNDg0ZjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDAxMzMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNTI1NGQ5ZTU0YmEyNTNkZTE1MjVlNmVmZjcxMmY5ZDJjMTA2MTBlM2JkYjhiOWY0MjU2Y2RkMzExNDQxMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6OfdeOym51SLXmaI92ZuqElZm7O4zAuW8HfHfnmNx8M) 要申请的，安全组开了没用

我联系了服务器提供商 ，他们那边表示端口出入口全部放行，包括25端口在内

**Comment by lujia1009** [comment]
> > > > 感觉像是云厂商把25的出口流量给关了
> > > 
> > > 
> > > 我服务器端口全部放行了啊
> > 
> > 
> > ![1721105961906](https://private-user-images.githubusercontent.com/73122677/348946093-0aa53c74-191e-4e58-9592-0d288d484f57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExODAzMDAsIm5iZiI6MTcyMTE4MDAwMCwicGF0aCI6Ii83MzEyMjY3Ny8zNDg5NDYwOTMtMGFhNTNjNzQtMTkxZS00ZTU4LTk1OTItMGQyODhkNDg0ZjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDAxMzMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNTI1NGQ5ZTU0YmEyNTNkZTE1MjVlNmVmZjcxMmY5ZDJjMTA2MTBlM2JkYjhiOWY0MjU2Y2RkMzExNDQxMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6OfdeOym51SLXmaI92ZuqElZm7O4zAuW8HfHfnmNx8M) 要申请的，安全组开了没用
> 
> 我联系了服务器提供商 ，他们那边表示端口出入口全部放行，包括25端口在内

现在有一个新问题：
[info][2024-07-17 10:14:53][ac1100026697291d9e7900019d69f8b0][/work/controllers/email/send.go:58]发送邮件
[error][2024-07-17 10:15:13][ac1100026697291d9e7900019d69f8b0][/work/utils/send/send.go:154]2165468532@qq.com%!(EXTRA string=域名mx记录查询失败)
[error][2024-07-17 10:15:15][ac1100026697291d9e7900019d69f8b0][/work/utils/send/send.go:209][0xc000067d20] 邮件投递失败dial tcp: lookup smtp.qq.com: i/o timeout
[error][2024-07-17 10:15:15][/work/hooks/framework/framework.go:112]params error json: cannot unmarshal object into Go struct field HookDTO.ErrMap of type error
[error][2024-07-17 10:15:15][/work/hooks/framework/framework.go:112]params error json: cannot unmarshal object into Go struct field HookDTO.ErrMap of type error
[error][2024-07-17 10:15:15][/work/hooks/framework/framework.go:112]params error json: cannot unmarshal object into Go struct field HookDTO.ErrMap of type error
