### ISSUE TITLE
EXTRA string=域名mx记录查询失败;  dial tcp: lookup smtp.gmail.com: i/o timeout

### ISSUE THREAD

**Issue by lujia1009** [Jinnrry/PMail#162]
无法正常收发邮件，错误信息如下：
域名mx记录查询失败

[info][2024-07-17 10:14:53][ac1100026697291d9e7900019d69f8b0][/work/controllers/email/send.go:58]发送邮件
[error][2024-07-17 10:15:13][ac1100026697291d9e7900019d69f8b0][/work/utils/send/send.go:154]2165468532@qq.com%!(EXTRA string=域名mx记录查询失败)
[error][2024-07-17 10:15:15][ac1100026697291d9e7900019d69f8b0][/work/utils/send/send.go:209][0xc000067d20] 邮件投递失败dial tcp: lookup smtp.qq.com: i/o timeout
[error][2024-07-17 10:15:15][/work/hooks/framework/framework.go:112]params error json: cannot unmarshal object into Go struct field HookDTO.ErrMap of type error
[error][2024-07-17 10:15:15][/work/hooks/framework/framework.go:112]params error json: cannot unmarshal object into Go struct field HookDTO.ErrMap of type error
[error][2024-07-17 10:15:15][/work/hooks/framework/framework.go:112]params error json: cannot unmarshal object into Go struct field HookDTO.ErrMap of type error

**域名解析记录正常，该解析的我都解析了**

**Comment by lujia1009** [comment]
![Uploading 微信图片_20240717102204.png…]()

**Comment by Jinnrry** [comment]
lookup 失败，检查你服务器dns设置

或者服务器上面执行nslookup smtp.gmail.com看看

**Comment by lujia1009** [comment]
> lookup 失败，检查你服务器dns设置
> 
> 或者服务器上面执行nslookup smtp.gmail.com看看

我重新部署后，发邮件一直提示dial tcp 203.205.219.57:25: i/o timeout。

**Comment by lujia1009** [comment]
> nslookup smtp.gmail.com

返回如下：
Non-authoritative answer:
Name:	smtp.gmail.com
Address: 142.250.102.108
Name:	smtp.gmail.com
Address: 2a00:1450:4025:401::6c

**Comment by lujia1009** [comment]
> lookup 失败，检查你服务器dns设置
> 
> 或者服务器上面执行nslookup smtp.gmail.com看看

我已经解决了

**Comment by maryjeck** [comment]
> > lookup 失败，检查你服务器dns设置
> > 或者服务器上面执行nslookup smtp.gmail.com看看
> 
> 我已经解决了

怎么解决的，我和你相反，我能发信，无法收信，163发来，在163上显示退回
