### ISSUE TITLE
mysql insert error: constraint failed: NOT NULL constraint failed: email.cron_send_time (1299)

### ISSUE THREAD

**Issue by muyiacc** [Jinnrry/PMail#165]
**请说明问题 / Describe the bug**
网页端发送邮件失败，提示：`constraint failed: NOT NULL constraint failed: email.cron_send_time (1299)`

**日志：**
```
pmail  | [info][2024-07-19 14:36:53][/work/controllers/email/send.go:194]mysql insert error: constraint failed: NOT NULL constraint failed: email.cron_send_time (1299)
```

根据这个日志可以看到mysql插入失败，但是我使用的是sqlite。

**配置文件：**
![图片](https://github.com/user-attachments/assets/2a736082-cb86-42d6-bbbe-47b02b38063a)

**Comment by Jinnrry** [comment]
最新版，已修复

**Comment by dzz10** [comment]
@Jinnrry 2.6.1  依旧有这个问题
[error][2024-07-26 13:41:17][ac185b4a66a336fc7fa2845436381eb0][/home/runner/work/PMail/PMail/server/smtp_server/read_content.go:235]db insert error:constraint failed: NOT NULL constraint failed: email.cron_send_time (1299)

**Comment by Jinnrry** [comment]
> @Jinnrry 2.6.1 依旧有这个问题 [error][2024-07-26 13:41:17][ac185b4a66a336fc7fa2845436381eb0][/home/runner/work/PMail/PMail/server/smtp_server/read_content.go:235]db insert error:constraint failed: NOT NULL constraint failed: email.cron_send_time (1299)

我翻了下代码diff，2.4.4版本开始，将数据库框架改成了xorm，修改过程中cron_send_time由not null改成了允许null，但是xorm在sqlite上好像不能自动同步这个表结构变化。可以尝试自己手动改下表结构。

下个版本我也会在这个位置加上默认值

**Comment by dzz10** [comment]
> > @Jinnrry 2.6.1 依旧有这个问题 [error][2024-07-26 13:41:17][ac185b4a66a336fc7fa2845436381eb0][/home/runner/work/PMail/PMail/server/smtp_server/read_content.go:235]db insert error:constraint failed: NOT NULL constraint failed: email.cron_send_time (1299)
> 
> 我翻了下代码diff，2.4.4版本开始，将数据库框架改成了xorm，修改过程中cron_send_time由not null改成了允许null，但是xorm在sqlite上好像不能自动同步这个表结构变化。可以尝试自己手动改下表结构。
> 
> 下个版本我也会在这个位置加上默认值

是的，我把sqlite数据库文件拿出来，给它改成允许为NULL就好了

**Comment by Jinnrry** [comment]
> > > @Jinnrry 2.6.1 依旧有这个问题 [error][2024-07-26 13:41:17][ac185b4a66a336fc7fa2845436381eb0][/home/runner/work/PMail/PMail/server/smtp_server/read_content.go:235]db insert error:constraint failed: NOT NULL constraint failed: email.cron_send_time (1299)
> > 
> > 
> > 我翻了下代码diff，2.4.4版本开始，将数据库框架改成了xorm，修改过程中cron_send_time由not null改成了允许null，但是xorm在sqlite上好像不能自动同步这个表结构变化。可以尝试自己手动改下表结构。
> > 下个版本我也会在这个位置加上默认值
> 
> 是的，我把sqlite数据库文件拿出来，给它改成允许为NULL就好了

我看xorm的文档，说的是会自动同步表结构变化的，我也没想到他同步不全。看来文档说的自动同步应该只有加字段会同步

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/PMail/releases/tag/v2.6.2 

已修复
