### ISSUE TITLE
客户端无法登录域名邮箱

### ISSUE THREAD

**Issue by lujia1009** [Jinnrry/PMail#166]
登录时，服务器端显示报错：2024/07/19 21:00:01 ERROR STLS Error %+v !BADKEY=EOF

**Comment by lujia1009** [comment]
我web后台，邮件可正常收发。目前就是第三方客户端无法登录域名邮箱

**Comment by Jinnrry** [comment]
有其他日志吗？就这一行日志，啥都看不出来啊

**Comment by lujia1009** [comment]
> 有其他日志吗？就这一行日志，啥都看不出来啊

smtp/server 2024/07/20 11:22:39 error handling 206.168.34.208:39882: read tcp 172.17.0.2:465->206.168.34.208:39882: read: connection reset by peer
smtp/server 2024/07/20 11:37:23 error handling 172.169.111.132:42588: tls: first record does not look like a TLS handshake
2024/07/20 11:46:18 ERROR STLS Error %+v !BADKEY=EOF
smtp/server 2024/07/20 11:48:27 error handling 206.168.34.119:56716: tls: client offered only unsupported versions: [302 301]
smtp/server 2024/07/20 11:48:29 error handling 206.168.34.119:56726: tls: client offered only unsupported versions: [301]
smtp/server 2024/07/20 11:48:31 error handling 206.168.34.119:53268: tls: client offered only unsupported versions: []

**Comment by lujia1009** [comment]
> > 有其他日志吗？就这一行日志，啥都看不出来啊
> 
> smtp/server 2024/07/20 11:22:39 error handling 206.168.34.208:39882: read tcp 172.17.0.2:465->206.168.34.208:39882: read: connection reset by peer smtp/server 2024/07/20 11:37:23 error handling 172.169.111.132:42588: tls: first record does not look like a TLS handshake 2024/07/20 11:46:18 ERROR STLS Error %+v !BADKEY=EOF smtp/server 2024/07/20 11:48:27 error handling 206.168.34.119:56716: tls: client offered only unsupported versions: [302 301] smtp/server 2024/07/20 11:48:29 error handling 206.168.34.119:56726: tls: client offered only unsupported versions: [301] smtp/server 2024/07/20 11:48:31 error handling 206.168.34.119:53268: tls: client offered only unsupported versions: []



> 有其他日志吗？就这一行日志，啥都看不出来啊

POP服务器和SMTP服务器的用户名和密码我都填了，分别对应pmail的账号密码

**Comment by lujia1009** [comment]
> 有其他日志吗？就这一行日志，啥都看不出来啊

这是不是跟Docker有关，这段报错信息：smtp/server 2024/07/20 22:18:54 error handling 113.100.231.202:12357: read tcp 172.17.0.2:465->113.100.231.202:12357: i/o timeout

**Comment by Jinnrry** [comment]
tls: client offered only unsupported versions: [301] 

用的什么客户端？好像是你的客户端不支持PMail的tls证书版本

客户端需要支持TLS1.3

**Comment by lujia1009** [comment]
> tls: client offered only unsupported versions: [301]
> 
> 用的什么客户端？好像是你的客户端不支持PMail的tls证书版本
> 
> 客户端需要支持TLS1.3

腾讯的QQ邮箱

**Comment by lujia1009** [comment]
> tls: client offered only unsupported versions: [301]
> 
> 用的什么客户端？好像是你的客户端不支持PMail的tls证书版本
> 
> 客户端需要支持TLS1.3

而且我用谷歌邮箱虽然可以登录域名邮箱，但是提示"安全等级可能不受支持"

**Comment by lujia1009** [comment]
> tls: client offered only unsupported versions: [301]
> 
> 用的什么客户端？好像是你的客户端不支持PMail的tls证书版本
> 
> 客户端需要支持TLS1.3

我使用目前市面上主流的客户都都无法登录！例如使用谷歌邮箱登录时，只能发件，不能收件，设置收件服务器时，提示"安全等级不受支持"。使用QQ邮箱客户端，直接无法登录。使用微软客户端，也是只能发件，不能收件。

**Comment by lujia1009** [comment]
> tls: client offered only unsupported versions: [301]
> 
> 用的什么客户端？好像是你的客户端不支持PMail的tls证书版本
> 
> 客户端需要支持TLS1.3

解决了，是Docker没有映射995端口，我直接复制的你教程的命令
