### ISSUE TITLE
如果只需要接收邮件，用腾讯云服务器，没有25端口，可以吗？

### ISSUE THREAD

**Issue by laoma2053** [Jinnrry/PMail#167]
搭建好了，只想分配邮箱地址，只用于接收邮件，不发送邮件，在腾讯云服务器部署，是否可以呢？

然后腾讯云文档说，465端口来收发邮件，需要如何设置？
![image](https://github.com/user-attachments/assets/b6bfefb0-4971-4995-b2b9-b0d8d5d509d1)

我现在已经部署到腾讯云服务器，但是无法发送邮件，也不能接收邮件
![image](https://github.com/user-attachments/assets/43faea3d-3921-4b52-9a1e-7c19d969d7d1)

**Comment by Jinnrry** [comment]
1、不可以
2、腾讯说的使用465是指调用其他邮箱服务商收发邮件，比如你通过465端口调用网易邮箱。你自己搭建邮箱服务端不可以
