### ISSUE TITLE
【功能请求】能不能实现一下邮件转发的插件

### ISSUE THREAD

**Issue by J3n5en** [Jinnrry/PMail#17]
【功能请求】能不能实现一下邮件转发的插件
习惯使用gmail备份邮件，尝试了一下做邮件转发插件，没做明白

大佬空了能不能做一下给参考参考。谢谢

**Comment by J3n5en** [comment]
赞，谢谢

**Comment by Jinnrry** [comment]
#21 在v2.2.0版本中已经实现这个功能了


![image](https://github.com/Jinnrry/PMail/assets/19919556/adc0092c-4350-4d2c-977b-3927a751aec5)

**Comment by J3n5en** [comment]
Cool！
