### ISSUE TITLE
一个比较严重的BUG，收件箱BUG问题。

### ISSUE THREAD

**Issue by lujia1009** [Jinnrry/PMail#175]
### 完整性要求 / Integrity requirements

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。
- [X] 我已经阅读了项目[Readme](https://github.com/Jinnrry/PMail/blob/master/README_CN.md)和[常见问题](https://github.com/Jinnrry/PMail/discussions/170)

### 版本

2.6.1

### 描述

**这个问题在WEB后台没有出现，但是任意的第三方客户端收件时会出现**

在第三方邮箱客户端登录域名邮箱时，收件箱会出现与其它域名邮箱共享的问题。
例如，我的域名邮箱是@fantecy.cn，我注册了两个域名邮箱分别是www@fantecy.cn和test@fantecy.cn
我使用其它邮箱(xxx@qq.com)给test@fantecy.cn发了封邮件
奇怪的是www@fantecy.cn的收件箱也能收到xxx@qq.com发来的邮件
但收件人是test@fantecy.cn，为什么www@fantecy.cn也可以收到邮箱

**我希望这个问题得到解决，如果无法解决我再考虑使用其它域名邮箱系统。首先我并不认为是客户端问题，因为其它主流客户端都出现这个问题，而且使用其它域名邮箱(如网易的企业邮箱)并没有这个问题。**

**我也希望作者在每次发布新版本前，先测试是否有问题，待版本完善之后再发布，否则这么多问题之下，使用体验非常糟糕。真的**

### 重现方式

1，注册两个域名邮箱A和B

使用第三方客户端登录域名邮箱，这里使用QQ邮箱为例
分别登录A和B

使用C邮箱给B发封邮件
B邮箱收到邮件
A邮箱也会收到，但正常来讲，A邮箱不应该收到的。

再注册一个新的域名邮箱E
用C给E发邮件
A,B,E同时收到邮件！！！！

### 服务端配置

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by lujia1009** [comment]
目前只能暂时使用网易的企业邮箱了，没有出现这个问题

**Comment by Jinnrry** [comment]
邮箱客户端是管理员账号登录的？

**Comment by lujia1009** [comment]
> 邮箱客户端是管理员账号登录的？

不是，我是在后台注册，然后用普通账号登录的

**Comment by Jinnrry** [comment]
用的什么客户端？

**Comment by lujia1009** [comment]
> 用的什么客户端？

QQ邮箱。

**Comment by lujia1009** [comment]
> 用的什么客户端？

我部署系统的时候，绑定了多个邮箱域名。我不知道是不是跟这个有关系，所以建议重现的时候，单域名和多域名都测试一遍。

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/PMail/releases/tag/v2.6.2 

已修复

**Comment by Fantecy** [comment]
> https://github.com/Jinnrry/PMail/releases/tag/v2.6.2
> 
> 已修复

然后多域名，同一个前缀的情况下，能不能不要共用收件箱。比如我绑定了两个域名a.com和b.com，前缀都是www。www@a.com和www@b.com不要共享收件箱

**Comment by Jinnrry** [comment]
> > https://github.com/Jinnrry/PMail/releases/tag/v2.6.2
> > 已修复
> 
> 然后多域名，同一个前缀的情况下，能不能不要共用收件箱。比如我绑定了两个域名a.com和b.com，前缀都是www。[www@a.com](mailto:www@a.com)和[www@b.com](mailto:www@b.com)不要共享收件箱

未来可以考虑
