### ISSUE TITLE
使用谷歌邮箱或微软邮箱，小米邮箱等客户端登录时，无法收件

### ISSUE THREAD

**Issue by Fantecy** [Jinnrry/PMail#179]
### 完整性要求 / Integrity requirements

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。
- [X] 我已经阅读了项目[Readme](https://github.com/Jinnrry/PMail/blob/master/README_CN.md)和[常见问题](https://github.com/Jinnrry/PMail/discussions/170)

### 版本

2.6.2

### 描述

使用谷歌邮箱或微软邮箱，小米邮箱客户端登录时，无法收件。
使用QQ邮箱登录时，收件正常。但其它客户端登录时，只能发件不能收件，即便在配置正确的情况下

服务端日志：
[warning][2024-07-28 12:18:10][ac11000266a5c68279cd0001f1d1e2b0][/work/pop3_server/action.go:34]not supported cmd request! cmd:AUTH args:[]

### 重现方式

已描述

### 服务端配置

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by Jinnrry** [comment]
谷歌、微软邮箱，是使用GMail、outlook客户端，还是使用代收信服务？

**Comment by Fantecy** [comment]
> 谷歌、微软邮箱，是使用GMail、outlook客户端，还是使用代收信服务？

  客户端
