### ISSUE TITLE
gmail邮件发送不出去，报PTR错误

### ISSUE THREAD

**Issue by bwb0101** [Jinnrry/PMail#181]
### 完整性要求 / Integrity requirements

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。
- [X] 我已经阅读了项目[Readme](https://github.com/Jinnrry/PMail/blob/master/README_CN.md)和[常见问题](https://github.com/Jinnrry/PMail/discussions/170)

### 版本

2.6.2

### 描述

日志：
[info][2024-07-31 16:43:50][675d4b6e66a9f9469c0e8cf2430c70b0][/home/runner/work/PMail/PMail/server/controllers/email/send.go:58]发送邮件
[error][2024-07-31 16:43:53][675d4b6e66a9f9469c0e8cf2430c70b0][/home/runner/work/PMail/PMail/server/utils/send/send.go:207][0xc000038520] 邮件投递失败550 5.7.25 [2401:3400:8000:1::69] The IP address sending this message does not
5.7.25 have a PTR record setup, or the corresponding forward DNS entry does
5.7.25 not match the sending IP. As a policy, Gmail does not accept
5.7.25 messages from IPs with missing PTR records. For more information, go
5.7.25 to
5.7.25  https://support.google.com/a?p=sender-guidelines-ip
5.7.25 To learn more about Gmail requirements for bulk senders, visit
5.7.25  https://support.google.com/a?p=sender-guidelines. d9443c01a7336-1fed7ee81f0si149452475ad.272 - gsmtp

域名配置：
![image](https://github.com/user-attachments/assets/b769b30b-8390-4142-b452-92684a3905a9)

### 重现方式

发送邮件到gmail

### 服务端配置

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by Jinnrry** [comment]
https://powerdmarc.com/zh/spf-record-lookup/

你可以用这个工具检查你的spf记录设置，你用ipv6的话需要把你的ipv6地址加上去，或者限制只用ipv4地址通信

**Comment by bwb0101** [comment]
配置上没有指定ip设置吧？

**Comment by Jinnrry** [comment]
目前没有强制ipv4的选项，你在spf记录里面加上你的v6地址把

**Comment by bwb0101** [comment]
行，我明天试试
