### ISSUE TITLE
手机客户端发送问题

### ISSUE THREAD

**Issue by l739217783** [Jinnrry/PMail#185]
### 完整性要求 / Integrity requirements

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。
- [X] 我已经阅读了项目[Readme](https://github.com/Jinnrry/PMail/blob/master/README_CN.md)和[常见问题](https://github.com/Jinnrry/PMail/discussions/170)

### 版本

2.6.2

### 描述

目前配置好所有选项，在Web管理界面的收发均正常
但是配置手机邮件客户端，不知道为什么收邮件正常，发邮件不是发到目标用户，而是进入自己的收件箱
有一个类似的issues（[手机客户端收发邮件问题 #54](https://github.com/Jinnrry/PMail/issues/54)），但是没有找到解决方法😅
例如，我域名邮箱是admin@linguoguang.com，往739217783@qq.com发送一封邮箱的话，结果不知道为啥是发给自己，能在admin@linguoguang.com的收件箱中找到这份发送给目标的邮件

### 重现方式

手机使用的是华为默认的电子邮件应用，采用README的配置，配置如图
![微信图片_20240806225641](https://github.com/user-attachments/assets/36b5109f-2c85-47d0-9e3a-101359b2280f)
![微信图片_20240806225649](https://github.com/user-attachments/assets/a4ba0aff-2864-49ff-9e49-00b4565bc7da)

### 服务端配置

Nginx：
```
 # 邮件
    server {
            listen 443 ssl http2;
            server_name mail.linguoguang.com;

            ssl_certificate      C:/Users/Administrator/Desktop/nginx-1.24.0/ssl/mail.linguoguang.com.pem;
            ssl_certificate_key  C:/Users/Administrator/Desktop/nginx-1.24.0/ssl/mail.linguoguang.com.key;

            ssl_session_cache    shared:SSL:1m;
            ssl_session_timeout  5m;
            ssl_protocols        TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
            ssl_ciphers          ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
            ssl_prefer_server_ciphers  on;

            location / {
                proxy_pass http://127.0.0.1:8367;
            }
        }

    server {
        listen 80;
        server_name mail.linguoguang.com;
        location /.well-known/{
            proxy_pass  http://127.0.0.1:8367;
            proxy_redirect     off;
            proxy_set_header   X-Real-IP        $remote_addr;
            proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        }
        location /{
            return 301 https://mail.linguoguang.com$request_uri;
        }
    }
 ```
 
 PMail:
 ```
 {
  "logLevel": "debug",
  "domain": "linguoguang.com",
  "domains": ["linguoguang.com"],
  "webDomain": "mail.linguoguang.com",
  "dkimPrivateKeyPath": "config/dkim/dkim.priv",
  "sslType": "1",
  "SSLPrivateKeyPath": "./config/ssl/mail.linguoguang.com.key",
  "SSLPublicKeyPath": "./config/ssl/mail.linguoguang.com_public.crt",
  "dbDSN": "./config/pmail.db",
  "dbType": "sqlite",
  "httpsEnabled": 2,
  "spamFilterLevel": 0,
  "httpPort": 8367,
  "httpsPort": 443,
  "weChatPushAppId": "",
  "weChatPushSecret": "",
  "weChatPushTemplateId": "",
  "weChatPushUserId": "",
  "tgBotToken": "",
  "tgChatId": "",
  "isInit": true,
  "webPushUrl": "",
  "webPushToken": ""
}

 ```

### 服务端日志

手机端发送邮件时候，显示的日志：

<details><pre><code>
[debug][2024-08-06 22:36:28][c0a8000266b234ec6ed01e8cefc52cb0][/home/runner/work
/PMail/PMail/server/smtp_server/smtp.go:29]新SMTP连接
[debug][2024-08-06 22:36:28][c0a8000266b234ec6ed01e8cefc52cb0][/home/runner/work
/PMail/PMail/server/smtp_server/smtp.go:104]Mail Success admin@linguoguang.com &
{Body: Size:0 RequireTLS:false UTF8:false Return: EnvelopeID: Auth:<nil>}
[debug][2024-08-06 22:36:28][c0a8000266b234ec6ed01e8cefc52cb0][/home/runner/work
/PMail/PMail/server/smtp_server/smtp.go:110]Rcpt Success 739217783@qq.com
[debug][2024-08-06 22:36:29][c0a8000266b234ec6ed01e8cefc52cb0][/home/runner/work
/PMail/PMail/server/smtp_server/read_content.go:33]收到邮件
[debug][2024-08-06 22:36:29][c0a8000266b234ec6ed01e8cefc52cb0][/home/runner/work
/PMail/PMail/server/smtp_server/read_content.go:40]开始执行插件ReceiveParseBefor
e！
[debug][2024-08-06 22:36:29][c0a8000266b234ec6ed01e8cefc52cb0][/home/runner/work
/PMail/PMail/server/smtp_server/read_content.go:47]开始执行插件ReceiveParseBefor
e End！
[debug][2024-08-06 22:36:31][c0a8000266b234ec6ed01e8cefc52cb0][/home/runner/work
/PMail/PMail/server/smtp_server/read_content.go:138]开始执行插件ReceiveParseAfte
r！
[debug][2024-08-06 22:36:31][c0a8000266b234ec6ed01e8cefc52cb0][/home/runner/work
/PMail/PMail/server/smtp_server/read_content.go:145]开始执行插件ReceiveParseAfte
r！End
[debug][2024-08-06 22:36:31][c0a8000266b234ec6ed01e8cefc52cb0][/home/runner/work
/PMail/PMail/server/smtp_server/read_content.go:205]开始入库！
[debug][2024-08-06 22:36:31][c0a8000266b234ec6ed01e8cefc52cb0][/home/runner/work
/PMail/PMail/server/smtp_server/read_content.go:161]开始执行邮件规则！
[debug][2024-08-06 22:36:31][c0a8000266b234ec6ed01e8cefc52cb0][/home/runner/work
/PMail/PMail/server/smtp_server/read_content.go:173]开始执行插件ReceiveSaveAfter
！
[debug][2024-08-06 22:36:31][c0a8000266b234ec6ed01e8cefc52cb0][/home/runner/work
/PMail/PMail/server/smtp_server/read_content.go:189]开始执行插件ReceiveSaveAfter
！End
</code></pre></details>

**Comment by Jinnrry** [comment]
这里是`c0a8000266b234ec6ed01e8cefc52cb0`这个trace的完整日志吗？检查下你的客户端smtp账号配置了吗？这里看起来是客户端没有发送登录命令，直接发送了邮件数据，没登录状态的smtp就当接收邮件处理了

**Comment by Jinnrry** [comment]
额。。我看到了，你客户端不有个“要求登录”的选项么，那个勾上，然后把账号密码填上

**Comment by l739217783** [comment]
不行，勾选上还是一样，发送会进入自己的收件箱，不知道什么原因，放弃折腾了。😅
