### ISSUE TITLE
发送邮件可以正常使用utf-8，接受邮件无法正确看到汉字。

### ISSUE THREAD

**Issue by EddieUZ** [Jinnrry/PMail#186]
### 完整性要求 / Integrity requirements

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。
- [X] 我已经阅读了项目[Readme](https://github.com/Jinnrry/PMail/blob/master/README_CN.md)和[常见问题](https://github.com/Jinnrry/PMail/discussions/170)

### 版本

最新

### 描述

接收文件看不到中文，全是？

![11111](https://github.com/user-attachments/assets/003c2e82-97a9-41f4-9c65-a72f0441229c)

### 重现方式

正常配置

### 服务端配置

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by Jinnrry** [comment]
1、浏览器什么环境，其他页面文字正常吗
2、服务器什么环境，安装中文字体了吗
3、什么数据库，数据库设置的什么字符集，数据DSN设置字符集了吗

**Comment by EddieUZ** [comment]
1.浏览器是正常能用的，什么环境我不知道。其他页面是可以的，或者说邮箱的英文是正常显示的，可能是编码用的ascll。

2.centos，我买的阿里云的，我安装了一个中文字体，没改观。
3.MySQL，数据库设置了utf-8，我的dsn是 root:123456@tcp(172.17.0.1:3306)/database_Pmail?parseTime=True&loc=Local

**Comment by EddieUZ** [comment]
[](url)

**Comment by EddieUZ** [comment]
![mmexport1723125634641.jpg](https://github.com/user-attachments/assets/3a354adc-4247-4a1f-a598-a61d17e4924b)

![mmexport1723125632513.jpg](https://github.com/user-attachments/assets/c8072383-b770-4960-82cc-82ff133544cc)

**Comment by EddieUZ** [comment]
![Screenshot_2024-08-08-22-02-14-70_5a42d52d30d60776c2ad16172ca3cc76.jpg](https://github.com/user-attachments/assets/3cd77b40-b40e-41bc-9ec2-bd3b7c6629c2)

收件箱是一对问号，但是英文可以正常顺序正常浏览。

**Comment by EddieUZ** [comment]
![mmexport1723126090792.jpg](https://github.com/user-attachments/assets/8b50cffd-3ec1-458f-a984-579dd54135f4)

我可以发送出去中文，接收邮箱也是中文显示。但是接受别人的中文是问号。

**Comment by EddieUZ** [comment]
![mmexport1723126394026.png](https://github.com/user-attachments/assets/53cb732c-d617-4e64-b1a8-d8f820295628)

作者，这个东西在磁盘的哪个地方？我找不到这个文件，配置不了。

**Comment by EddieUZ** [comment]
终于弄好了。以下是我排查问题用到的指令。
CENT OS-YUM安装:yum install -y yum-utils

安装docker compose（最前面不要有$）:
sudo curl -L "https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
可执行权限：sudo chmod +x /usr/local/bin/docker-compose
创建软链：sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose


创建mkdir docker-compose.yml
使用 nano 编辑器：nano docker-compose.yml
然后复制粘贴后按ctrl+x退出，enter确认文件名


启动docker-compose up -d


进入容器 
docker exec -it qmail /bin/sh

查看 config 目录的内容 ls config/cat config
vi编辑 vi config.json
vi i键编辑 :wq保存并退出


进入mysql客户端 mysql -u root -p123456


pmail 运行：docker run -d --name qmail -p 25:25 -p 80:80 -p 443:443 -p 110:110 -p 465:465 -p 995:995 -v $(pwd)/config:/work/config ghcr.io/jinnrry/pmail:latest


删除所有已经停止的容器docker rm $(docker ps -a -q)
 ifconfig命令Linux查询ip
确定MySQL编码：SHOW VARIABLES LIKE 'character_set%';
修改MySQL数据库编码ALTER DATABASE database_Pmail DEFAULT CHARACTER SET utf8mb4;
修改MySQL数据表编码ALTER TABLE table_name CONVERT TO CHARACTER SET utf8mb4;
查看MySQL表：select * from email;


查看MySQL表的编码
SELECT TABLE_SCHEMA, TABLE_NAME, CCSA.character_set_name
FROM information_schema.TABLES T,
     information_schema.`COLLATION_CHARACTER_SET_APPLICABILITY` CCSA
WHERE CCSA.collation_name = T.table_collation
  AND T.table_schema = 'database_Pmail'  -- 替换为你的数据库名
  AND T.table_name = 'email'; -- 替换为你的表名（这行删去就是全部的表）
  
  
  
  
  问题在于MySQL数据库的编码是欧文编码，需要多次将数据库内的表改为utf8，不能单纯的改database_Pmail的编码.
  作者的config.json文件的路径是进入docker后启动容器，输入ls就可以看到，不要随便改，因为可能会导致主机的这个文件也被改，MySQL连接语句不要带编码解释句。
