### ISSUE TITLE
什么时候能支持一下webhook

### ISSUE THREAD

**Issue by DaiMaoZuiKeAi** [Jinnrry/PMail#188]
想要在收到邮件时将邮件发送到webhook地址推送

**Comment by Jinnrry** [comment]
以前有这个功能，最近版本删除了。https://github.com/Jinnrry/PMail/wiki/%E6%8F%92%E4%BB%B6%E5%BC%80%E5%8F%91%E8%AF%B4%E6%98%8E

可以参考插件文档，自己写一个插件，三五行代码的事
