### ISSUE TITLE
作者能否提供一个示例的docker-compose.yml文件或者使用docker运行容器的命令

### ISSUE THREAD

**Issue by muyiacc** [Jinnrry/PMail#19]
我使用这条docker启动容器，出现了容器无法启动
`sudo docker run -p 25:5 -p 5780:80 -p 4343:443 -v ./config:/config --name pmail2 ghcr.io/jinnrry/pmail`

输出信息为创建一系列的表，最后的信息为
CREATE INDEX sessions_expiry_idx ON sessions (expiry);
[info][2023-09-04 11:56:11][/work/http_server/https_server.go:42]Http Server Start
[fatal][2023-09-04 11:56:11][/work/smtp_server/main.go:64]open config/ssl/public.crt: no such file or directory

接着我使用提供的程序直接运行，会提示80端口被占用，因为我已经安装了nginx 。

作者能理解这个我表达的意思吗

**Comment by Jinnrry** [comment]
你这个docker命令没问题，报错是因为你配置文件里面的路径不对。你检查下你配置文件里面的SSL证书文件路径

**Comment by 8x48** [comment]
我也遇到这个问题了，但是证书路径是对的

**Comment by 8x48** [comment]
试了下

> 我使用这条docker启动容器，出现了容器无法启动 `sudo docker run -p 25:5 -p 5780:80 -p 4343:443 -v ./config:/config --name pmail2 ghcr.io/jinnrry/pmail`
> 
> 输出信息为创建一系列的表，最后的信息为 CREATE INDEX sessions_expiry_idx ON sessions (expiry); [info][2023-09-04 11:56:11][/work/http_server/https_server.go:42]Http Server Start [fatal][2023-09-04 11:56:11][/work/smtp_server/main.go:64]open config/ssl/public.crt: no such file or directory
> 
> 接着我使用提供的程序直接运行，会提示80端口被占用，因为我已经安装了nginx 。
> 
> 作者能理解这个我表达的意思吗

刚看了下docker里面的目录结构，容器里面配置文件目录是/work/config，改一下就行

**Comment by Jinnrry** [comment]
> 试了下
> 
> > 我使用这条docker启动容器，出现了容器无法启动 `sudo docker run -p 25:5 -p 5780:80 -p 4343:443 -v ./config:/config --name pmail2 ghcr.io/jinnrry/pmail`
> > 输出信息为创建一系列的表，最后的信息为 CREATE INDEX sessions_expiry_idx ON sessions (expiry); [info][2023-09-04 11:56:11][/work/http_server/https_server.go:42]Http Server Start [fatal][2023-09-04 11:56:11][/work/smtp_server/main.go:64]open config/ssl/public.crt: no such file or directory
> > 接着我使用提供的程序直接运行，会提示80端口被占用，因为我已经安装了nginx 。
> > 作者能理解这个我表达的意思吗
> 
> 刚看了下docker里面的目录结构，容器里面配置文件目录是/work/config，改一下就行

额。。我知道了，我打包镜像的时候不小心把测试用的config文件放进去，因此会有问题，我改下Dockerfile
