### ISSUE TITLE
Set DNS步骤多加一条记录

### ISSUE THREAD

**Issue by qux-bbb** [Jinnrry/PMail#195]
在"Set Domain"步骤里，设置了"Web Domain"  
![web_mail](https://github.com/user-attachments/assets/3ef6d1df-565a-4f82-a9ed-21ca6addc186)  

在"Set DNS"步骤里，没有生成对应的DNS records，如果没有"Web Domain"相应记录的话，后续运行会出错  
![set_dns](https://github.com/user-attachments/assets/c90c67ba-1f94-429a-8916-18d62c44b137)  

所以建议在"Set DNS"步骤里多加一条解析"Web Domain"相应域名的记录

**Comment by Jinnrry** [comment]
确实，有空我加上

**Comment by Jinnrry** [comment]
v2.6.5 已添加
