### ISSUE TITLE
端口占用问题，导致服务关闭

### ISSUE THREAD

**Issue by dongchenxuan** [Jinnrry/PMail#198]
### 完整性要求 / Integrity requirements

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。
- [X] 我已经阅读了项目[Readme](https://github.com/Jinnrry/PMail/blob/master/README_CN.md)和[常见问题](https://github.com/Jinnrry/PMail/discussions/170)

### 版本

v2.6.4

### 描述

端口被重复绑定

### 重现方式

服务重启会出现 
panic: listen tcp :995: bind: address already in use

### 服务端配置

<details><pre><code>

</code></pre></details>

### 服务端日志

[info][2024-09-03 13:16:43][/home/runner/work/PMail/PMail/server/pop3_server/pop3server.go:27]POP3 With TLS Server Start On Port :995
[info][2024-09-03 13:16:43][/home/runner/work/PMail/PMail/server/smtp_server/smtp.go:147]Starting Smtp With SSL Server Port: :465
panic: listen tcp :995: bind: address already in use

**Comment by Jinnrry** [comment]
程序是先输出端口信息，然后再占用端口，并不是程序重复占用两次端口。

`netstatus -tunlop | grep 995` 检查你服务器端口占用情况

**Comment by dongchenxuan** [comment]
进过检查，端口没有被其他进程占用

**Comment by dongchenxuan** [comment]
端口无占用的情况，也通过修改
