### ISSUE TITLE
自定义背景颜色

### ISSUE THREAD

**Issue by eternallyproud** [Jinnrry/PMail#210]
目前的Pmail背景是与浏览器外观颜色一致的

- 当用户选择浅色外观时，显示正常

![image](https://github.com/user-attachments/assets/f22a9c93-b5bc-4f4c-8399-fb2d85be67cb)

- 当用户选择神色外观时，显示异常

![image](https://github.com/user-attachments/assets/21ee683b-60b1-46a9-8b5c-c2375449efd9)

希望能添加自定义背景颜色的功能，应该改一点前端就好，也不会很占空间

**Comment by Jinnrry** [comment]
#119

**Comment by Jinnrry** [comment]
#119 重复

**Comment by eternallyproud** [comment]
错了哥，没在open里搜
