### ISSUE TITLE
邮件转发

### ISSUE THREAD

**Issue by MxxApp** [Jinnrry/PMail#214]
你好，邮件转发后是否可以携带原始邮件人的信息，比如用Poste设置catch-all,转发后，收件可以看到原始的收件人是哪个地址，现在pmail转发过来后，收件人就是设置的转发收件地址，不能知道原始收件人是谁，不容易分辨邮件来源

**Comment by Jinnrry** [comment]
确实保留原始收件人地址合理一点，等我有空改改逻辑

**Comment by Jinnrry** [comment]
v2.7.4 转发邮件将保留原信息
