### ISSUE TITLE
新BUG反馈，一个昵称问题导致发件失败的BUG

### ISSUE THREAD

**Issue by lujia1009** [Jinnrry/PMail#216]
### 完整性要求 / Integrity requirements

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。
- [X] 我已经阅读了项目[Readme](https://github.com/Jinnrry/PMail/blob/master/README_CN.md)和[常见问题](https://github.com/Jinnrry/PMail/discussions/170)

### 版本

2.7.4

### 服务端配置

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

### 描述

在发件时，如果修改了发件人昵称，就会导致发件失败，接口会返回错误信息：params error
在网页发件时会出现这个问题，客户端暂时不清楚。

**我想对作者说的话：Pmail从我刚使用到现在，已经发现了无数问题和一些缺陷，我可以感受到作者不是在很认真的写这个项目，项目看起来像是一堆屎山代码堆积起来的一个项目，很多的BUG。我希望作者在今后每发布一个版本前，一定要先进行各种测试，其次项目的架构设计要合理**

### 重现方式

在网页端发件时，点击发件人选项，修改默认的发件人昵称，这时候再发件，发送失败，接口返回101，错误信息为params error。
从老版本已经就有这个问题，我以为新版本应该修复了，但是并没有

**Comment by Jinnrry** [comment]
代码是开源的，你觉得bug多，你觉得需要重构，你自己动手就行。我从来没有说过保证多少SLA保证稳定啥的，这个项目本来就只是当玩具项目写的。后续迭代这些功能，95%都是我自己用不上的。

我自己经历有限，没那么多经历做100%覆盖的测试，后续的更新纯粹是看到有人开Issue反馈，然后顺手帮忙加的而已，本来我自己也没有这些功能的需求。我自己空余时间有限，周末还得陪老婆孩子，偶尔能抽个把小时支持几个新特性开发就已经很不容易了。如果你在意稳定性，那建议选其他带商业支持的项目。

这个项目！不保证稳定性！！

**Comment by MxxApp** [comment]
支持作者，首先感谢作者辛苦的付出，pmail小巧，节省资源，能满足作为邮件服务器的大部分功能，需求更多功能可以用其它的替代品，比如我没发现pmail之前，用的就是Poste，你觉得pmail不行，如果自己有能力就创作个更好的出来，没必要否定别人的付出

**Comment by shidahuilang** [comment]
> ### 完整性要求 / Integrity requirements
> * [x]  我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。[x]  我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。[x]  我搜索了issues，没有发现已提出的类似问题。[x]  我已经阅读了项目[Readme](https://github.com/Jinnrry/PMail/blob/master/README_CN.md)和[常见问题](https://github.com/Jinnrry/PMail/discussions/170)
> 
> ### 版本
> 2.7.4
> 
> ### 服务端配置
> ### 服务端日志
> ### 描述
> 在发件时，如果修改了发件人昵称，就会导致发件失败，接口会返回错误信息：params error 在网页发件时会出现这个问题，客户端暂时不清楚。
> 
> **我想对作者说的话：Pmail从我刚使用到现在，已经发现了无数问题和一些缺陷，我可以感受到作者不是在很认真的写这个项目，项目看起来像是一堆屎山代码堆积起来的一个项目，很多的BUG。我希望作者在今后每发布一个版本前，一定要先进行各种测试，其次项目的架构设计要合理**
> 
> ### 重现方式
> 在网页端发件时，点击发件人选项，修改默认的发件人昵称，这时候再发件，发送失败，接口返回101，错误信息为params error。 从老版本已经就有这个问题，我以为新版本应该修复了，但是并没有

那你可以自己去写啊·你别用啊
