### ISSUE TITLE
iOS端收信格式错乱

### ISSUE THREAD

**Issue by linyuancode** [Jinnrry/PMail#218]
### 完整性要求 / Integrity requirements

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。
- [X] 我已经阅读了项目[Readme](https://github.com/Jinnrry/PMail/blob/master/README_CN.md)和[常见问题](https://github.com/Jinnrry/PMail/discussions/170)

### 版本

2.7.4

### 服务端配置

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

### 描述

此前有反应过该bug，作者给出了大致猜测，但是经过近期使用，发现格式错乱的邮件远远不止GitHub验证邮件，很多大公司的邮件还有验证邮件都有该错误。此前由于大部分验证邮件以验证码为主，尚能使用，但是对于有些链接验证邮件就只能去网页端打开了。希望作者能考虑进一步排查一下原因。
格式错乱邮件示例如下图：
![IMG_0592](https://github.com/user-attachments/assets/a403c00d-bf2e-42e4-b8b6-f3c8438d3f1a)

### 重现方式

在GitHub添加pmail邮箱，使用iOS端收取该验证邮件是最有效的重现方法。其他一些大企业邮件部分错乱暂时还未找到规律。

**Comment by Jinnrry** [comment]
#212 我上次查了半天，实在是没找出哪里的问题。主要是涉及发件方（github），展示方（第三方客户端），这2边也没啥日志报错信息啥的可以看，我在中间，我看我转发的数据，都是原封不动的转发过去的，但就是格式不对。我也没找出哪里有问题
