### ISSUE TITLE
邮件转发失败

### ISSUE THREAD

**Issue by cccqcccq** [Jinnrry/PMail#220]
### 完整性要求 / Integrity requirements

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。
- [X] 我已经阅读了项目[Readme](https://github.com/Jinnrry/PMail/blob/master/README_CN.md)和[常见问题](https://github.com/Jinnrry/PMail/discussions/170)

### 版本

2.7.4

### 服务端配置

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>
[info][2024-11-02 00:12:27][/home/runner/work/PMail/PMail/server/dto/parsemail/dkim.go:95]Valid signature for: qq.com
[error][2024-11-02 00:12:28][ac1000036724fdeb1a46ee6ba613ffb0][/home/runner/work/PMail/PMail/server/utils/send/send.go:114][0xc0001ad160] 邮件投递失败550 Mail content denied [MJ8vvB3Z9HILDyk+wodtP4MX11azy2kRSERV7gfPvneArAnaGVv31DttVmD2vtJv1Q== IP: 服务器ip]. https://service.mail.qq.com/detail/122/171.
[error][2024-11-02 00:12:28][ac1000036724fdeb1a46ee6ba613ffb0][/home/runner/work/PMail/PMail/server/services/rule/rule.go:86]Forward Error:以下收件人投递失败：qq号码@qq.com

</code></pre></details>

### 描述

使用规则配置邮件转发尝试了包含、等于后一直没等到邮件查看日志提示错误了，但是直接发送邮件可以正常发送，qq邮箱可以收到，转发时不行

### 重现方式

刚配置完设置转发规则。

**Comment by Jinnrry** [comment]
https://service.mail.qq.com/detail/122/171

服务端日志里面有腾讯服务器的返回。打开那个地址就能看到原因
