### ISSUE TITLE
发送国内邮箱没问题但是会在垃圾箱里，但发到国外的GMAIL,OUTLOOK,会退信。

### ISSUE THREAD

**Issue by jilefo** [Jinnrry/PMail#226]
### 完整性要求 / Integrity requirements

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。
- [X] 我已经阅读了项目[Readme](https://github.com/Jinnrry/PMail/blob/master/README_CN.md)和[常见问题](https://github.com/Jinnrry/PMail/discussions/170)

### 版本

2.7.5

### 服务端配置

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

### 描述

发送国内邮箱没问题但是会在垃圾箱里，但发到国外的GMAIL,OUTLOOK,会退信。

### 重现方式

发送国内邮箱没问题但是会在垃圾箱里，但发到国外的GMAIL,OUTLOOK,会退信。

**Comment by HoneyWhiteCloud** [comment]
私有域的邮件容易被当作为垃圾邮件，为正常现象

**Comment by Jinnrry** [comment]
使用类似 [spamhaus](https://check.spamhaus.org/) 的服务检查IP是否干净
