### ISSUE TITLE
能否增加功能：主机映射到docker端口的修改

### ISSUE THREAD

**Issue by muyiacc** [Jinnrry/PMail#23]
经过几次docker搭建的测试，发现80，443端口不能修改主机其他端口的映射，否则会发生不能生成证书，访问web界面失败，

我先使用80:80 443:443 端口，docker搭建生成了证书，后修改了主机映射的端口，在生成证书那一步通过，复制之前生成的证书，最后web界面却无法访问

我的主机因为需要nginx来实现反向代理，所以主机的80，443端口就被占用了，这个测试还是我把nginx服务停掉之后测试的。

能把主机端口修改为自定义的吗

**Comment by AlwaysZmx** [comment]
我也遇到了同样的问题，希望早日修复

**Comment by Jinnrry** [comment]
生成证书的时候，必须保证80端口是通的，无论你加不加代理。Let's Encrypt需要访问你的域名，然后校验域名归属。这个是不能修改的

**Comment by Jinnrry** [comment]
如果你还有其他网站的话，nginx里面加规则，通过域名分流，总之你得保证Let's Encrypt服务器能够通过域名访问到你
