### ISSUE TITLE
需要一个catch all的功能

### ISSUE THREAD

**Issue by wuyilingwei** [Jinnrry/PMail#230]
如果有邮件没有发到任意一个邮箱，应该有一个捕获所有邮件的选项

**Comment by wuyilingwei** [comment]
比如有一个默认的邮箱应该来处理所有发到域下的，但是不是任何一个邮箱的

**Comment by Jinnrry** [comment]
现在admin账号就是捕获所有未匹配的邮件呀

**Comment by Jinnrry** [comment]
收件的时候会先检查是否有账号匹配，如果有账号匹配邮件就会给那个账号，如果不匹配就丢个管理员账号

**Comment by wuyilingwei** [comment]
啊，没有看见这方面的说明（）而且我给admin关了（乐）
希望补一个说明，最好能自定义账号。
那这个issue我就关了

**Comment by Jinnrry** [comment]
在配置页面创建的第一个账号就是管理员账号，这个账号你不叫admin也行
