### ISSUE TITLE
Sudo and https

### ISSUE THREAD

**Issue by naddika** [Jinnrry/PMail#25]
Even if I specify 8080 for the http port, it'll still  `sudo` to be able to the 25th port. Does it then require `sudo` no matter what? 

Also, I want to run it on a server where there'll be other ordinary websites. So I can't allow PMail to use 443 port  Can PMail  be put behind reverse proxy such as nginx, with http only?

How to disable https then? Remove `https` from the config?

**Comment by Jinnrry** [comment]
1、The program needs to receive mail through the smtp service.  Smtp protocol runs on port 25, so port 25 must be used. Root privileges are required by the Linux system.

https://www.staldal.nu/tech/2007/10/31/why-can-only-root-listen-to-ports-below-1024/

2、You can disable https by changing `httpsEnabled` to `2` in the configuration file.
