### ISSUE TITLE
服务器端口和dns记录

### ISSUE THREAD

**Issue by zale-lee** [Jinnrry/PMail#26]
1.希望可以在readme里面加上服务器需要开的端口，分为必须开的端口和自选开的端口，比如必须开的端口smtp对应的端口25，http端口80.
2.界面上显示的dns记录在godaddy上不能添加，两个hostname是-的不能添加，hostname不能填写-。

**Comment by Jinnrry** [comment]
1、readme的端口说明加上了
2、我那个 - 的意思是这项不填😅 不是说要填一个减号进去

**Comment by zale-lee** [comment]
1.我看是在配置那一块，我个人希望是单独出来一块。这不重要，这只是我个人习惯而已。
2.我还以为要填-进去呢。在godaddy上这一项是必填。
不知道有没有类似roumap的东西存在？我在梳理这个项目的逻辑，看看我能不能参与进去。
我猜你也是后端为主，会前端。

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/PMail/blob/master/server/http_server/https_server.go#L36
https://github.com/Jinnrry/PMail/blob/master/server/http_server/http_server.go
http服务的路由定义在这里，看代码可以从这里开始看

https://github.com/Jinnrry/PMail/blob/master/server/smtp_server/read_content.go#L23
smtp服务的入口在这里，smtp服务开发的话参考这个测试用例：https://github.com/Jinnrry/PMail/blob/master/server/smtp_server/read_content_test.go#L376

**Comment by zale-lee** [comment]
哦了

**Comment by dianso** [comment]
> 1、readme的端口说明加上了 2、我那个 - 的意思是这项不填😅 不是说要填一个减号进去

CF的域名，这里必须填，我填写@可以吗？
