### ISSUE TITLE
收到很多垃圾邮件，请问如何屏蔽？

### ISSUE THREAD

**Issue by muyiacc** [Jinnrry/PMail#30]
最近发现收到很多垃圾邮件，是怎么回事呀
![图片](https://github.com/Jinnrry/PMail/assets/115904774/dade9c91-91cc-40bf-9d24-eaaa286ea118)

**Comment by Jinnrry** [comment]
配置文件中可以修改垃圾邮件过滤级别
`"spamFilterLevel": 0,// 垃圾邮件过滤级别，0不过滤、1 spf dkim 校验均失败时过滤，2 spf校验不通过时过滤`
你可以打开数据库看看这个邮件的spf和dkim校验是否通过（email表的spf_check和dkim_check字段）

目前只支持协议层的伪造邮件过滤。不支持基于内容检测的垃圾邮件过滤。如果你需要根据内容过滤的话可以设置一个正则收信规则，匹配正则后移到分组或者删除
