### ISSUE TITLE
smtp地址是什么

### ISSUE THREAD

**Issue by muyiacc** [Jinnrry/PMail#31]
大佬，smtp地址是什么呀，最近想用在博客用于发信

**Comment by Jinnrry** [comment]
假设你的朋友A使用网易邮箱给你发邮件，那么网易的服务器得知道把邮件发到哪个服务器，哪个端口去吧。网易投递邮件的地址就是smtp地址

**Comment by muyiacc** [comment]
哪pmail的第smtp是什么呀

**Comment by Jinnrry** [comment]
smtp.你的域名
