### ISSUE TITLE
消息推送如何使用

### ISSUE THREAD

**Issue by muyiacc** [Jinnrry/PMail#32]
"weChatPushAppId": "", // 微信推送appid
"weChatPushSecret": "", // 微信推送秘钥
"weChatPushTemplateId": "", // 微信推送模板id
"weChatPushUserId": "", // 微信推送用户id
"tgChatId": "", // telegram 推送chatid
"tgBotToken": "", // telegram 推送 token

这些怎么获取和使用

**Comment by Jinnrry** [comment]
微信的推送Api https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Template_Message_Interface.html

Tg推送：https://t.me/BotFather
