### ISSUE TITLE
Can multiple copies of PMail be run on the same VPS with no issue?

### ISSUE THREAD

**Issue by zigomi** [Jinnrry/PMail#37]
I want to use PMail for multiple domains. 

If I run multiple installations, let's say, from "/opt/Pmail-1", "/opt/Pmail-2", "/opt/Pmail-3"... won't they mess up with other? Will everything work well? 

Some email-project such as Mail-in-the-Box, and others I don't remember which, require that it be installed on an **empty server** and **only one copy**. Otherwise, it won't work properly.

**Comment by Jinnrry** [comment]
No, you can only run one instance. This is restricted by the SMTP protocol, not by the programme now, only programmes listening on port 25 can receive mail.
