### ISSUE TITLE
windows v2.2.6 amd64 自动配置ssl报错

### ISSUE THREAD

**Issue by taotaoli123** [Jinnrry/PMail#40]
域名配置没问题, 一直报这个错误, 谁遇到过, 给回复一下.

at /home/runner/work/PMail/PMail/server/services/setup/ssl/ssl.go:124 error: one or more domains had a problem: [smtp.xx.cab] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 49.xx.xx.50: Fetching http://smtp.xx.cab/.well-known/acme-challenge/TIYN75vemNRhLYiV9M7y0kV9RreBD4uZNZ0a7zkEaTc: Timeout during connect (likely firewall problem)

**Comment by Jinnrry** [comment]
Timeout during connect (likely firewall problem)

连接Acme服务器超时了，你的机器在国内吧，是不是被GFW拦截了

**Comment by taotaoli123** [comment]
是国内的, 但是直连cmd窗口日志的Acme接口网址是可以正常访问的. [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/27942568xxxx

**Comment by taotaoli123** [comment]
抓包自动ssl配置这一步,http://smtp.xx.cab/api/setuppost 提交内容是这样的{
  "action": "set",
  "step": "ssl",
  "ssl_type": "0",
  "key_path": "./config/ssl/private.key",
  "crt_path": "./config/ssl/public.crt"
}
但/config/ssl/private.key和/config/ssl/public.crt 2个文件是不存在的,不知道是本来就不存在, 还是什么情况.
请求返回的正文是这样的
{
    "errorNo": 500,
    "errorMsg": "at /home/runner/work/PMail/PMail/server/services/setup/ssl/ssl.go:124\nerror: one or more domains had a problem:\n[smtp.xx.cab] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 49.81.55.50: Fetching http://smtp.xx.cab/.well-known/acme-challenge/PP8z7Mt9JNHq9ySx4POkeS0u--fXYc_wrD0IJt1VVfc: Timeout during connect (likely firewall problem)\n[stmp.xx.cab] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for stmp.xx.cab - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for stmp.xx.cab - check that a DNS record exists for this domain\n",
    "data": ""
}

**Comment by Jinnrry** [comment]
你域名是刚刚才把解析配上去的？有报错没找到解析记录

**Comment by taotaoli123** [comment]
> 你域名是刚刚才把解析配上去的？有报错没找到解析记录

解析等一天还是一样的报错
