### ISSUE TITLE
我用独角数卡的邮件配置了pm，但是测试发件却把邮件发到了我pm的收件箱

### ISSUE THREAD

**Issue by 547555909** [Jinnrry/PMail#43]
我在独角数卡的后台配置了pmail的smtp邮箱地址作为发件服务器，然后给我的邮箱发生测试邮件，结果在我的pmail收件箱里收到了测试邮件
![1698903292073](https://github.com/Jinnrry/PMail/assets/19320063/22aa2557-1eb9-41ed-b9be-c1b41c587db0)
![1698903326366](https://github.com/Jinnrry/PMail/assets/19320063/1d7d5d2a-5f96-4654-837f-fdd4811cd012)
我自己手动用pm发件箱发送邮件给我的邮箱是能成功的

**Comment by 547555909** [comment]
而且我在我QQ邮箱上查了，没有收到邮件，垃圾箱也没有

**Comment by Jinnrry** [comment]
PMail目前不支持邮件转发

**Comment by 547555909** [comment]
您发给我的邮件我已收到，我会尽快回复您的

**Comment by 547555909** [comment]
> PMail目前不支持邮件转发

不是转发，我是希望pm作为发件方，比如发送我独角数卡的卡密给购买者。
举例来说，比如a消费者买了一个卡密，他留了邮箱a.qq.com
我希望我这边用pm发送邮件给他的邮箱，邮件内容就是他的卡密信息

**Comment by Jinnrry** [comment]
你填在其他系统用smtp协议发件就是转发功能。PMail目前不支持转发。你想程序用PMail发件的话可以用调api直接发

https://github.com/Jinnrry/PMail/wiki/%E5%90%8E%E7%AB%AF%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3#6-emailsend

**Comment by 547555909** [comment]
> 你填在其他系统用smtp协议发件就是转发功能。PMail目前不支持转发。你想程序用PMail发件的话可以用调api直接发
> 
> https://github.com/Jinnrry/PMail/wiki/%E5%90%8E%E7%AB%AF%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3#6-emailsend

好的，期待未来能支持转发功能
