### ISSUE TITLE
求并集是不是写错了

### ISSUE THREAD

**Issue by Owen-Zhang** [Jinnrry/PMail#45]
// Merge 求并集
func Merge[T any](slice1, slice2 []T) []T {
	s1Len := len(slice1)

	slice3 := make([]T, s1Len+len(slice2))
	for i, t := range slice1 {
		slice3[i] = t
	}

	for i, t := range slice2 {
		slice3[s1Len+i] = t
	}

	return slice3
}
这个感觉不是并集呢， 并集是要将两个集合中相同的部分 只保留一份的

**Comment by Jinnrry** [comment]
新建一个数组，长度为s1的长度+s2的长度

循环s1，把s1的数据写入s3
循环s2，把s2的数据写入s3

返回s3

这怎么会是交集呢

**Comment by Owen-Zhang** [comment]
哈哈， 这是从你们的代码中找出来的

**Comment by Owen-Zhang** [comment]
可能是代码的注释写错了， 其实本意不是那个意思
