### ISSUE TITLE
初始化的时候,选择mysql不会导入数据库文件!

### ISSUE THREAD

**Issue by maxbad** [Jinnrry/PMail#50]
空数据库的时候, 在执行 `show tables` 的时候会返回err :missing destination name Tables_in_email_server in *[]*db.tables

**Comment by maxbad** [comment]
发现了问题,好像数据库表名称不能自定义.这里写死了,只能是pmail
```
type tables struct {
	TablesInPmail string `db:"Tables_in_pmail"`
}
```

**Comment by maxbad** [comment]
还有就是 `server/config/tables/mysql/data/user.sql`   和其他几个都是空文件, 导入的时候也会触发panic, 应该要过滤掉空文件.

**Comment by Jinnrry** [comment]
mysql show tables返回字段名没法改，只能写死。配置的时候我记得我专门说明过必须叫pmail

**Comment by maxbad** [comment]
如果必须固定数据库表名, 那么界面最好是搞只4个编辑框,填写数据库IP,端口,账号,密码, 表名不可修改,固定pmail

**Comment by Jinnrry** [comment]
panic重发了一个2.3.4版本，已经修复了。交互等下次有空我再重新设计下

**Comment by maxbad** [comment]
ok了
