### ISSUE TITLE
runtime error when try to run PMail in docker environment 

### ISSUE THREAD

**Issue by keekychen** [Jinnrry/PMail#53]
# docker run -p 25:25 -p 80:80 -p 443:443 -p 110:110 -p 465:465 -v $(pwd)/config:/work/config ghcr.io/jinnrry/pmail:latest
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x9507f5]

goroutine 1 [running]:
pmail/cron_server.Start()
        /work/cron_server/ssl_update.go:14 +0x15
main.main()
        /work/main.go:84 +0x351
[info][2023-11-23 17:29:12][/work/main.go:76]***************************************************
[info][2023-11-23 17:29:12][/work/main.go:77]***        Server Start Success Version:2.3.4

[info][2023-11-23 17:29:12][/work/main.go:78]***        Git Commit Hash:  
[info][2023-11-23 17:29:12][/work/main.go:79]***        Build TimeStamp: 2023-11-23 14:23:53 
[info][2023-11-23 17:29:12][/work/main.go:80]***        Build GoLang Version: go version go1.21.4 linux/amd64 
[info][2023-11-23 17:29:12][/work/main.go:81]***************************************************

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/PMail/releases/tag/v2.3.4

Had fixed. Try again, pls.
