### ISSUE TITLE
客户端功能完善

### ISSUE THREAD

**Issue by perry-le** [Jinnrry/PMail#60]
**有什么问题？ / Describe the solution you'd like**

就是可否写一份客户端连接该 PMali 的教程 像IMAP POP虽然在文档中写了大概的填写方法 像 issues-44 提到了该问题但是比较乱 希望作者可以出一个PMali配置教程客户端步骤 （安卓/苹果） 感谢！！！

**Comment by Jinnrry** [comment]
这需要教程？？？？？？？

打开客户端，选择pop3/smtp协议连接，输入你的域名，填写账号密码，点击确定
