### ISSUE TITLE
国内拉不动docker image啊

### ISSUE THREAD

**Issue by lgzcoollg** [Jinnrry/PMail#62]
**有什么问题？ / Describe the solution you'd like**

国内拉不动docker image啊

**Comment by Jinnrry** [comment]
你不挂代理，国内拉得动docker image才是有问题！

**Comment by lgzcoollg** [comment]
> 你不挂代理，国内拉得动docker image才是有问题！

...国内这是不合规的，公司网络不允许 ;-(
