### ISSUE TITLE
smtp

### ISSUE THREAD

**Issue by Sakura2tap** [Jinnrry/PMail#65]
想咨询一下 如何通过第三方软件比如foxmail，用smtp的方式登入！

**Comment by Jinnrry** [comment]
https://support.huaweicloud.com/clientog-koomail/0003.html

**Comment by Sakura2tap** [comment]
那这个邮件密码的话，是web登入管理台的密码吗，还是在哪里可以生成！

**Comment by Jinnrry** [comment]
是登陆密码，PMail没有隔离登陆密码和第三方客户端密码

**Comment by Sakura2tap** [comment]
我同不加密的25端口，会报错Failed: 523 5.7.10 TLS is required ，SMTP客户端是否可以配置TLS！谢谢
