### ISSUE TITLE
提个不成熟的小建议

### ISSUE THREAD

**Issue by alimataat** [Jinnrry/PMail#66]
建议发件人做一下格式验证，不然容易发到自己邮箱

**Comment by Jinnrry** [comment]
校验发件人？发到自己邮箱不应该是校验收件人吗？

**Comment by alimataat** [comment]
```
程序判断逻辑是登陆账号和发件人前缀相同且发件域名是服务器域名。如果条件为false就会当成收件处理
```
发件人格式不正确，也会当成收件处理。或者逻辑优化一下，当成收件处理让人有点懵，个人觉得直接报错出来用户体验更好

**Comment by Jinnrry** [comment]
哦哦，懂了，确实不太合理，我有空改改，好几个issues都这里导致的
