### ISSUE TITLE
绑定域名无法访问

### ISSUE THREAD

**Issue by chengdada123** [Jinnrry/PMail#67]
**请说明问题 / Describe the bug**
设置好之后访问设置的域名，提示重定向次数太多，不过照说跟几级域名没关系（使用的是三级域名）。
**如何复现 / To Reproduce**

使用docker 部署的。
启动容器之后，进入设置页，按照提示设置完之后。访问域名就无法访问
PS:域名已正确解析。

**你预期的行为 / Expected behavior**
预期可以正常访问。
**贴上你的配置文件 / Program configuration file contents**
<details>
  <summary>config.json</summary>

```
这里贴上你的配置文件内容。
Copy the contents of your configuration file here.
```

</details>

**日志信息 / Log**
<details>
  <summary>log</summary>

```
这里贴上问题相关日志
Copy the contents of your log here.

```

</details>

**Comment by Jinnrry** [comment]
程序日志呢？

**Comment by chengdada123** [comment]
日志显示正常。
![image](https://github.com/Jinnrry/PMail/assets/59160585/1c2c971d-f13c-494c-b5c1-2076c1b2d62c)

**Comment by chengdada123** [comment]
收发邮件正常，我只能使用https://+ip 访问web
不清楚是不是证书的问题。

**Comment by Jinnrry** [comment]
nslook 你的域名

看下dns解析对不

**Comment by chengdada123** [comment]
肯定对，收发邮件都正常的。

**Comment by chengdada123** [comment]
问题找到了，是由于域名是在cf解析的,解析的时候打开了小云朵，也就是开了cdn,所以导致出现上述问题。谢谢！
