### ISSUE TITLE
2.0.3.4的releases只有源码

### ISSUE THREAD

**Issue by jacksixth** [Jinnrry/PMail#7]
![image](https://github.com/Jinnrry/PMail/assets/42532036/956f6093-7f41-4f8c-af92-fa955ea4ea85)

**Comment by Jinnrry** [comment]
这个版本只是加了github的action配置，没有任何业务代码修改，编译文件用上一个版本的就行

**Comment by Jinnrry** [comment]
github 流水线配置的release时触发，为了触发编译所以重新发了一个版本

**Comment by jacksixth** [comment]
ok 谢谢
