### ISSUE TITLE
大佬，有没有正确的smtp配置示范？

### ISSUE THREAD

**Issue by zisanjun** [Jinnrry/PMail#70]
目前我自行配置，均会出现各种报错

**Comment by Jinnrry** [comment]
SMTP需要配置啥？你按照生成的配置随便改改就行呀

**Comment by zisanjun** [comment]
填在第三方的配置，第三方客户端用smtp发信会报错

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/PMail/blob/master/README_CN.md#%E7%AC%AC%E4%B8%89%E6%96%B9%E9%82%AE%E4%BB%B6%E5%AE%A2%E6%88%B7%E7%AB%AF%E9%85%8D%E7%BD%AE

**Comment by zisanjun** [comment]
465+ssl，会出现报错504 5.7.4 Unsupported authentication mechanism，大佬这个要咋解决

**Comment by zisanjun** [comment]
咱pmail的身份验证机制是？

**Comment by Jinnrry** [comment]
> 咱pmail的身份验证机制是？

没什么机制，只有一套账号密码，你初始化的时候设置的管理员账号就是你web端登陆账号密码，也是你smtp登陆账号密码

**Comment by Jinnrry** [comment]
> 465+ssl，会出现报错504 5.7.4 Unsupported authentication mechanism，大佬这个要咋解决

你用的什么客户端？我去试试

**Comment by zisanjun** [comment]
https://www.cnblogs.com/sz-wenbin/p/11112553.html 查阅了资料，我怀疑是Go官方包的问题

**Comment by zisanjun** [comment]
> > 465+ssl，会出现报错504 5.7.4 Unsupported authentication mechanism，大佬这个要咋解决
> 
> 你用的什么客户端？我去试试

网站程序用smtp发信

**Comment by zisanjun** [comment]
QQ邮箱客户端也无法登录 是不是我哪里配置不对呀

**Comment by Jinnrry** [comment]
Golang原始的SMTP实现确实很多bug，这个项目SMTP协议实现有2部分。
1、https://github.com/Jinnrry/PMail/blob/master/server/utils/smtp/smtp.go
这个是我fork Golang语言官方是SMTP实现代码，修了几个bug的版本。这个SMTP实现主要用于发邮件

2、https://github.com/emersion/go-smtp 
这个是另外一个开源的SMTP协议实现，这个主要用于收邮件和客户端登陆转发等

刚刚我抓包看了下，emersion/go-smtp 这个包EHLO命令实现确实和主流邮箱服务端表现不一致

**Comment by zisanjun** [comment]
辛苦大佬了，期待解决~

**Comment by Jinnrry** [comment]
> > > 465+ssl，会出现报错504 5.7.4 Unsupported authentication mechanism，大佬这个要咋解决
> > 
> > 
> > 你用的什么客户端？我去试试
> 
> 网站程序用smtp发信

你网站程序是什么编程语言的，用的什么包？有复现代码吗？

**Comment by Jinnrry** [comment]
v2.3.7已修复

**Comment by zisanjun** [comment]
辛苦大佬！！

**Comment by zisanjun** [comment]
454 4.7.0 password error at \/work\/smtp_server\/smtp.go:75\r


现在465+ssl会出现这个错误，好像是密码错误，大佬这个我要去哪里修改呀

**Comment by Jinnrry** [comment]
这个是你初始化的时候设置的密码，你如果不记得这个密码了，那直接改你的数据库吧，或者重新初始化。

user表里面的password字段，加密规则是`md5(md5(password+"pmail") +"pmail2023")`

**Comment by Jinnrry** [comment]
有服务端日志吗

**Comment by zisanjun** [comment]
--ce3ff8d17aea9b8961ea7d443819c833
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: base64

PGRpdiBzdHlsZT0ibWluLWhlaWdodDo1NTBweDsgcGFkZGluZzogMTAwcHggNTVweCAyMDBweDsi
Pui/meaYr+S4gOWwgeadpeiHqlJlbGF4RHJhbWHnmoTmoKHpqozpgq7ku7Ys55So5LqO5qCh6aqM
6YKu5Lu26YWN572u5piv5ZCm5q2j5bi4ITwvZGl2Pg==


--ce3ff8d17aea9b8961ea7d443819c833--



smtp/server 2024/01/29 16:54:30 panic serving 172.17.0.1:50438: runtime error: invalid memory address or nil pointer dereference
goroutine 137 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/emersion/go-smtp.(*Conn).handle.func1()
	/go/pkg/mod/github.com/jinnrry/go-smtp@v0.20.1/conn.go:96 +0xa5
panic({0xa0b120?, 0x1186b50?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
pmail/dto/parsemail.(*Email).BuildBytes(0xc000223c20, 0xc00006d870?, 0x1)
	/work/dto/parsemail/email.go:306 +0xe04
pmail/utils/send.Send(0xc000024640, 0xc000223c20)
	/work/utils/send/send.go:112 +0x45
pmail/smtp_server.(*Session).Data(0xc000024690, {0xd234e0, 0xc0001ab920})
	/work/smtp_server/read_content.go:71 +0x685
github.com/emersion/go-smtp.(*Conn).handleData(0xc0002ea580, {0x0?, 0x0?})
	/go/pkg/mod/github.com/jinnrry/go-smtp@v0.20.1/conn.go:905 +0x191
github.com/emersion/go-smtp.(*Conn).handle(0xc0002ea580, {0xc0002f5460?, 0xc0002ea580?}, {0x0, 0x0})
	/go/pkg/mod/github.com/jinnrry/go-smtp@v0.20.1/conn.go:137 +0x198
github.com/emersion/go-smtp.(*Server).handleConn(0xc0001cc120, 0xc0002ea580)
	/go/pkg/mod/github.com/jinnrry/go-smtp@v0.20.1/server.go:206 +0x2c7
github.com/emersion/go-smtp.(*Server).Serve.func1()
	/go/pkg/mod/github.com/jinnrry/go-smtp@v0.20.1/server.go:162 +0xdc
created by github.com/emersion/go-smtp.(*Server).Serve in goroutine 10
	/go/pkg/mod/github.com/jinnrry/go-smtp@v0.20.1/server.go:159 +0x225
[info][2024-01-29 16:54:30][ac11000265b767c656200001a742aeb0][/work/smtp_server/read_content.go:46]邮件原始内容: Date: Mon, 29 Jan 2024 16:54:30 +0800
Return-Path: oeatv@oeatv.com
From: =?utf-8?B?b2VhdHY=?= <oeatv@oeatv.com>
To: =?utf-8?B?ODQ2ODAzOTY=?= <84680396@qq.com>
Cc: 
Bcc: 
Reply-To: <>
Subject: =?utf-8?B?6L+Z5piv5LiA5bCB5p2l6IeqUmVsYXhEcmFtYeeahOmCruS7tg==?= 
Message-ID: <cf43cc780b72dad392d4f90dfced88a8@oeatv@oeatv.com>
X-Priority: 3
X-Mailer: Mailer (https://github.com/txthinking/Mailer)
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="6edc2ef285d93010a080caccc858c67b"

--6edc2ef285d93010a080caccc858c67b
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: base64

PGRpdiBzdHlsZT0ibWluLWhlaWdodDo1NTBweDsgcGFkZGluZzogMTAwcHggNTVweCAyMDBweDsi
Pui/meaYr+S4gOWwgeadpeiHqlJlbGF4RHJhbWHnmoTmoKHpqozpgq7ku7Ys55So5LqO5qCh6aqM
6YKu5Lu26YWN572u5piv5ZCm5q2j5bi4ITwvZGl2Pg==


--6edc2ef285d93010a080caccc858c67b
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: base64

PGRpdiBzdHlsZT0ibWluLWhlaWdodDo1NTBweDsgcGFkZGluZzogMTAwcHggNTVweCAyMDBweDsi
Pui/meaYr+S4gOWwgeadpeiHqlJlbGF4RHJhbWHnmoTmoKHpqozpgq7ku7Ys55So5LqO5qCh6aqM
6YKu5Lu26YWN572u5piv5ZCm5q2j5bi4ITwvZGl2Pg==


--6edc2ef285d93010a080caccc858c67b--



smtp/server 2024/01/29 16:54:30 panic serving 172.17.0.1:38120: runtime error: invalid memory address or nil pointer dereference
goroutine 140 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/emersion/go-smtp.(*Conn).handle.func1()
	/go/pkg/mod/github.com/jinnrry/go-smtp@v0.20.1/conn.go:96 +0xa5
panic({0xa0b120?, 0x1186b50?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
pmail/dto/parsemail.(*Email).BuildBytes(0xc0003787e0, 0xc00006d870?, 0x1)
	/work/dto/parsemail/email.go:306 +0xe04
pmail/utils/send.Send(0xc000024c30, 0xc0003787e0)
	/work/utils/send/send.go:112 +0x45
pmail/smtp_server.(*Session).Data(0xc000024c80, {0xd234e0, 0xc0001abca0})
	/work/smtp_server/read_content.go:71 +0x685
github.com/emersion/go-smtp.(*Conn).handleData(0xc0002ea630, {0x0?, 0x0?})
	/go/pkg/mod/github.com/jinnrry/go-smtp@v0.20.1/conn.go:905 +0x191
github.com/emersion/go-smtp.(*Conn).handle(0xc0002ea630, {0xc00038e060?, 0xc0002ea630?}, {0x0, 0x0})
	/go/pkg/mod/github.com/jinnrry/go-smtp@v0.20.1/conn.go:137 +0x198
github.com/emersion/go-smtp.(*Server).handleConn(0xc0001cc120, 0xc0002ea630)
	/go/pkg/mod/github.com/jinnrry/go-smtp@v0.20.1/server.go:206 +0x2c7
github.com/emersion/go-smtp.(*Server).Serve.func1()
	/go/pkg/mod/github.com/jinnrry/go-smtp@v0.20.1/server.go:162 +0xdc
created by github.com/emersion/go-smtp.(*Server).Serve in goroutine 10
	/go/pkg/mod/github.com/jinnrry/go-smtp@v0.20.1/server.go:159 +0x225
smtp/server 2024/01/29 16:55:03 handler error: read tcp 172.17.0.2:465->172.17.0.1:41504: i/o timeout

**Comment by zisanjun** [comment]
看起来在SMTP服务器处理请求时出现了一个panic错误，该错误指示无效的内存地址或空指针解引用。panic发生在pmail/dto/parsemail.(*Email).BuildBytes函数中

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/PMail/releases/tag/v2.3.7.1

这个版本里面修复了空指针异常，可以再看看

**Comment by zisanjun** [comment]
马上测试，辛苦佬

**Comment by zisanjun** [comment]
docker更新了吗

**Comment by Jinnrry** [comment]
docker没有发lastest，得用这个
https://github.com/Jinnrry/PMail/pkgs/container/pmail/172143642?tag=prev2.3.7.1

**Comment by zisanjun** [comment]
反馈：报告，佬，2.3.7.1版本已解决smtp发信问题，非常牛逼

**Comment by Jinnrry** [comment]
好的，tks，2.3.7.1已经改成releas版本了
