### ISSUE TITLE
搜狐邮箱投递失败

### ISSUE THREAD

**Issue by alimataat** [Jinnrry/PMail#72]
日志如下
Jan 23 17:14:04 vm pmail[1036667]: [warning][2024-01-23 17:14:04][0a00012b65af835512b5d17bb69a53b0][/home/runner/work/PMail/PMail/server/utils/send/send.go:158]SMTP Send Error! Error:smtp: server doesn't support STARTTLS
Jan 23 17:14:04 vm pmail[1036667]: [error][2024-01-23 17:14:04][0a00012b65af835512b5d17bb69a53b0][/home/runner/work/PMail/PMail/server/utils/send/send.go:182][0xc00034a7c0] 邮件投递失败smtp: server doesn't support STARTTLS

**Comment by Jinnrry** [comment]
server doesn't support STARTTLS

这么离谱的吗，都2024年了搜狐邮箱居然不支持STARTTLS。没TLS加密的话，邮件内容完全明文传输，出于安全考虑，PMail强制要求TLS。但还有不支持STARTTLS的，我也是没想到。

**Comment by alimataat** [comment]
中国电信189邮箱 也是 server doesn't support STARTTLS

**Comment by Jinnrry** [comment]
那等我有空改下吧，改成允许非TLS传输

**Comment by alimataat** [comment]
2925无限邮 上榜！

**Comment by alimataat** [comment]
新浪邮箱 上榜！

**Comment by Jinnrry** [comment]
v2.3.7已修复
