### ISSUE TITLE
有一个bug

### ISSUE THREAD

**Issue by alimataat** [Jinnrry/PMail#73]
发送邮件报错， 如下
Jan 25 15:44:25 vm pmail[1036667]: [warning][2024-01-25 15:44:25][0a00012b65b211536a41d17bf15a39b0][/home/runner/work/PMail/PMail/server/utils/send/send.go:158]SMTP Send Error! Error:tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match tommx.tom.com.
Jan 25 15:44:25 vm pmail[1036667]: [error][2024-01-25 15:44:25][0a00012b65b211536a41d17bf15a39b0][/home/runner/work/PMail/PMail/server/utils/async/async.go:68]goroutine panic:runtime error: index out of range [0] with length 0
Jan 25 15:44:25 vm pmail[1036667]:  goroutine 159 [running]:
Jan 25 15:44:25 vm pmail[1036667]: runtime/debug.Stack()
Jan 25 15:44:25 vm pmail[1036667]:         /opt/hostedtoolcache/go/1.21.4/x64/src/runtime/debug/stack.go:24 +0x5e
Jan 25 15:44:25 vm pmail[1036667]: pmail/utils/async.(*Async).HandleErrRecover(0xc00043afc0, {0xa5fb40?, 0xc0000d2738})
Jan 25 15:44:25 vm pmail[1036667]:         /home/runner/work/PMail/PMail/server/utils/async/async.go:68 +0x109
Jan 25 15:44:25 vm pmail[1036667]: pmail/utils/async.(*Async).Process.func1.1()
Jan 25 15:44:25 vm pmail[1036667]:         /home/runner/work/PMail/PMail/server/utils/async/async.go:45 +0x3a
Jan 25 15:44:25 vm pmail[1036667]: panic({0xa5fb40?, 0xc0000d2738?})
Jan 25 15:44:25 vm pmail[1036667]:         /opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:914 +0x21f
Jan 25 15:44:25 vm pmail[1036667]: pmail/utils/send.domainMatch({0xc000074b53, 0x7}, {0x0, 0x0, 0xc0001bbf20?})
Jan 25 15:44:25 vm pmail[1036667]:         /home/runner/work/PMail/PMail/server/utils/send/send.go:259 +0x28d
Jan 25 15:44:25 vm pmail[1036667]: pmail/utils/send.Send.func1({0xa3cd60?, 0x97a4a5?})
Jan 25 15:44:25 vm pmail[1036667]:         /home/runner/work/PMail/PMail/server/utils/send/send.go:170 +0x459
Jan 25 15:44:25 vm pmail[1036667]: pmail/utils/async.(*Async).WaitProcess.func1({0x0?, 0x0?})
Jan 25 15:44:25 vm pmail[1036667]:         /home/runner/work/PMail/PMail/server/utils/async/async.go:37 +0x5a
Jan 25 15:44:25 vm pmail[1036667]: pmail/utils/async.(*Async).Process.func1()
Jan 25 15:44:25 vm pmail[1036667]:         /home/runner/work/PMail/PMail/server/utils/async/async.go:48 +0x58
Jan 25 15:44:25 vm pmail[1036667]: created by pmail/utils/async.(*Async).Process in goroutine 163
Jan 25 15:44:25 vm pmail[1036667]:         /home/runner/work/PMail/PMail/server/utils/async/async.go:42 +0xa5

**Comment by Jinnrry** [comment]
v2.3.7已修复
