### ISSUE TITLE
database设置没有说明

### ISSUE THREAD

**Issue by McKinleyLu** [Jinnrry/PMail#80]
后台报错，配置数据库没有进度，docker后台看了，一会儿吐一点东西，这咋回事啊

**Comment by Jinnrry** [comment]
报什么错？

**Comment by McKinleyLu** [comment]
数据库构建时到处都是错误。。。

**Comment by McKinleyLu** [comment]
![7](https://github.com/Jinnrry/PMail/assets/45777553/ba4fdfa8-6a1d-4783-88a3-d9e4f51bec81)

**Comment by Jinnrry** [comment]
贴个日志？

**Comment by Jinnrry** [comment]
MySQL版本是多少？你这难道还是5.6以下的版本？

**Comment by McKinleyLu** [comment]
at /work/services/setup/ssl/ssl.go:126 error: 
one or more domains had a problem: [smtp.xxxcom] acme: error: 400 :: urn:ietf:params:acme:error:dns :: 
DNS problem: NXDOMAIN looking up A for smtp.xxx.com - check that a DNS record exists for this domain; 
DNS problem: NXDOMAIN looking up AAAA for smtp.xxx.com - check that a DNS record exists for this domain

smtp.xxx.com 明明解析到服务器很久了（一个多小时，目前还是显示不行，不知道是哪里的问题）

**Comment by McKinleyLu** [comment]
![Snipaste_2024-02-08_19-10-41](https://github.com/Jinnrry/PMail/assets/45777553/143bc510-fac7-48c5-b4b6-b70adb2e4f75)
后端问题显示如下

**Comment by McKinleyLu** [comment]
已经完成，但是最后不知道用户名和密码，无法登录，数据库中的密码和用户名也不对

**Comment by Jinnrry** [comment]
你配置的管理员账号密码就是，忘记了的话删掉config目录重新配置

**Comment by McKinleyLu** [comment]
谢谢大佬，以上问题均解决

但是不知道数据库怎么回事，明明在后台可以看到发件、收件均没有问题，但是数据库报错，发件箱和收件箱均为空
![AA](https://github.com/Jinnrry/PMail/assets/45777553/1e84c683-c3ab-4e96-9747-19952fe265dd)
![BB](https://github.com/Jinnrry/PMail/assets/45777553/13e17ab0-b7e2-43bf-af5f-2f41d3495358)
![CC](https://github.com/Jinnrry/PMail/assets/45777553/f3065080-9266-475a-b063-7279042e9b08)

**Comment by Jinnrry** [comment]
你现在是啥版本的mysql?

**Comment by McKinleyLu** [comment]
Mysql 版本为 8.0.27

**Comment by Jinnrry** [comment]
备份info日志，备份数据库，这两个地方都能恢复
