### ISSUE TITLE
使用docker run,安装失败

### ISSUE THREAD

**Issue by lijunwyf21** [Jinnrry/PMail#83]
使用docker run,安装失败

先执行： docker pull ghcr.io/jinnrry/pmail:latest
执行： docker run -p 35:25 -p 85:80 -p 445:443 -p 110:110 -p 465:465 -p 995:995 -v /home/datum/dockerapp/pmail/config:/work/config ghcr.io/jinnrry/pmail:latest

报错： /bin/sh: /work/pmail: not found

希望能正常安装，运行。另外，希望能提供非docker的安装方式的说明文档。多谢

**Comment by Jinnrry** [comment]
是x86架构吗？最新版本为了支持arm架构，刚刚调整了docker镜像

**Comment by Jinnrry** [comment]
非docker安装的话，你直接下载对应二进制文件运行即可。linux系统的话使用supervisor或systemd管理进程。windows的话使用计划任务管理进程。不同系统区别比较大，我也没法统一提供说明

**Comment by Jinnrry** [comment]
2.3.8版本为了支持arm平台，由alpine系统改成了ubuntu系统编译，但是ubuntu和alpine动态链接库不一样导致无法运行

**Comment by Jinnrry** [comment]
已修复，可以再试试
