### ISSUE TITLE
没考虑二级域名做服务器啊

### ISSUE THREAD

**Issue by kpddadyo72419** [Jinnrry/PMail#9]
RT

**Comment by Jinnrry** [comment]
这，确实没考虑过。目前使用二级域名卡哪里了？

**Comment by xiaooloong** [comment]
猜您想找「三级域」

「二级域」 https://zh.wikipedia.org/wiki/%E4%BA%8C%E7%BA%A7%E5%9F%9F

**Comment by kpddadyo72419** [comment]
> 这，确实没考虑过。目前使用二级域名卡哪里了？

你自己试试，二级域名确实有问题，具体啥问题我忘记了  ，上了个mailu的方案，就是有点重，op做的简单还是比较想用的

**Comment by cht870422** [comment]
> > 这，确实没考虑过。目前使用二级域名卡哪里了？
> 
> 你自己试试，二级域名确实有问题，具体啥问题我忘记了 ，上了个mailu的方案，就是有点重，op做的简单还是比较想用的

你mailu 的 域名解析  TLSA 怎么处理的
