### ISSUE TITLE
控制台的时间显示的系统不一致导致崩溃

### ISSUE THREAD

**Issue by scriptxiaozi** [Jinnrry/PMail#90]
![image](https://github.com/Jinnrry/PMail/assets/91516959/af833157-7b51-459f-bc58-25c310897663)

![image](https://github.com/Jinnrry/PMail/assets/91516959/dcc3af3d-061b-4cad-a91c-12aa4a4144da)

在使用客户端设置服务器时之后崩溃

**Comment by Jinnrry** [comment]
服务器是怎么部署的？有复现方法吗

**Comment by scriptxiaozi** [comment]
windows部署，在没有任何配置的情况下，直接打开应该时区就不对，配置之后也一样，和系统时间相差六小时。
用自带的前端网页发邮件没有问题，尝试用客户端连接服务器就会崩溃

**Comment by Jinnrry** [comment]
你第二个图好像没传上来，是windows server版本吗？有具体的版本号吗。

程序运行的时候会获取当前操作系统时区，Linux系统的话类似https://github.com/Jinnrry/PMail/blob/master/DockerfileGithubAction#L20 这样设置。但是我也从来没用过Windows Server，不清楚怎么设置。这个报错应该是拿不到当前系统时区

**Comment by scriptxiaozi** [comment]
服务器时winserver2016
我自己电脑win11
都是打开exe看到的日志时间都是伦敦时间，我再换台电脑试试

**Comment by scriptxiaozi** [comment]
> 服务器时winserver2016 我自己电脑win11 都是打开exe看到的日志时间都是伦敦时间，我再换台电脑试试

另一台win10 也是同样的问题

**Comment by Jinnrry** [comment]
https://studygolang.com/articles/22725

应该是这个问题，我今晚找台windows电脑测试下，没问题的话今晚重新发个修复版本

**Comment by scriptxiaozi** [comment]
非常感谢！

**Comment by Jinnrry** [comment]
2.4.2版本试试

**Comment by scriptxiaozi** [comment]
> 2.4.2版本试试

可以了，感谢
