### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by maxbad** [Jinnrry/PMail#91]
**请说明问题 / Describe the bug**

**如何复现 / To Reproduce**
1. 克隆仓库,直接docker build

**你预期的行为 / Expected behavior**

**贴上你的配置文件 / Program configuration file contents**
<details>
  <summary>config.json</summary>

```
这里贴上你的配置文件内容。
Copy the contents of your configuration file here.
```

</details>

**日志信息 / Log**
<details>
  <summary>log</summary>

```
这里贴上问题相关日志
Copy the contents of your log here.

```

</details>

**Comment by maxbad** [comment]
是不是因为 server 目录下面没有 .git信息呢,

**Comment by maxbad** [comment]
好像是少一个 `COPY server .`

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/PMail/commit/505b3df773600bb3a5952fa5dddbceee40299747

是的，少了一个COPY，已经改了

**Comment by maxbad** [comment]
dockerfile里还可以加上
EXPOSE 25
EXPOSE 80
EXPOSE 110
EXPOSE 443
EXPOSE 465
EXPOSE 995

**Comment by Jinnrry** [comment]
嗯，是的，忘记了，有空我加上
