### ISSUE TITLE
通过手机客户端登录,发送的短信, 在草稿箱里.

### ISSUE THREAD

**Issue by maxbad** [Jinnrry/PMail#92]
**请说明问题 / Describe the bug**
邮件是发送成功了, 但是登录管理网页,没有在发件箱,而在草稿箱

还有就是可以支持下多个账号在手机客户端登录吗?

**如何复现 / To Reproduce**

**你预期的行为 / Expected behavior**

**贴上你的配置文件 / Program configuration file contents**
<details>
  <summary>config.json</summary>

```
这里贴上你的配置文件内容。
Copy the contents of your configuration file here.
```

</details>

**日志信息 / Log**
<details>
  <summary>log</summary>

```
这里贴上问题相关日志
Copy the contents of your log here.

```

</details>

**Comment by Jinnrry** [comment]
有日志和复现步骤吗？

**Comment by Jinnrry** [comment]
最新版本已修复
