### ISSUE TITLE
80启动 被nginx占用，无法启动，有没有自定义启动端口命令操作方法？

### ISSUE THREAD

**Issue by APPX-Studio** [Jinnrry/PMail#95]
**有什么问题？ / Describe the solution you'd like**
<img width="884" alt="image" src="https://github.com/Jinnrry/PMail/assets/49307767/6063a7c0-bd37-4ac7-b464-bf78f08506e5">

**Comment by APPX-Studio** [comment]
谢谢 本地没问题，搬到服务器上端口冲突

**Comment by Jinnrry** [comment]
`./PMail -p 8080`

启动的时候增加`-p`参数自定义端口

**Comment by mcxxvv** [comment]
Windows Server怎么搞一键启动没办法自定义端口

**Comment by Jinnrry** [comment]
> Windows Server怎么搞一键启动没办法自定义端口

什么叫一键启动？难道有什么启动不是一键吗
