### ISSUE TITLE
关于个性化转发规则

### ISSUE THREAD

**Issue by DTAO0** [Jinnrry/PMail#96]
大佬你好，我目前想把收到的所有邮件正文的验证码提取出来，然后通过tg机器人推送，请问有添加这个功能的计划吗？
或者您方便有偿教我下吗？实在头疼😭

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/PMail/wiki/%E6%8F%92%E4%BB%B6%E5%BC%80%E5%8F%91%E8%AF%B4%E6%98%8E

自己这个插件，然后正则匹配一下不就行了？现在已经有tg推送机器人了，你加个正则上去就行了
