### ISSUE TITLE
刚搭建一天 垃圾邮件规则没有效果

### ISSUE THREAD

**Issue by APPX-Studio** [Jinnrry/PMail#97]
**有什么问题？ / Describe the solution you'd like**
<img width="476" alt="image" src="https://github.com/Jinnrry/PMail/assets/49307767/64923b45-d949-4947-b370-f06b213cf882">
<img width="1139" alt="image" src="https://github.com/Jinnrry/PMail/assets/49307767/c6674bb5-d479-4131-963e-2033131485d0">

**Comment by Jinnrry** [comment]
点编辑看看具体怎么配置的呢，或者帖一下数据库里面rule表的记录

**Comment by Jinnrry** [comment]
最新版本已修复
